/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CheckoutSessionCreate,
    CheckoutSessionCreateFromJSON,
    CheckoutSessionCreateToJSON,
} from '../models/CheckoutSessionCreate';
import {
    type CheckoutSessionCreateBody,
    CheckoutSessionCreateBodyFromJSON,
    CheckoutSessionCreateBodyToJSON,
} from '../models/CheckoutSessionCreateBody';
import {
    type CheckoutSessionGet,
    CheckoutSessionGetFromJSON,
    CheckoutSessionGetToJSON,
} from '../models/CheckoutSessionGet';
import {
    type CheckoutSessionPayBody,
    CheckoutSessionPayBodyFromJSON,
    CheckoutSessionPayBodyToJSON,
} from '../models/CheckoutSessionPayBody';
import {
    type CheckoutSessionSelectMethodBody,
    CheckoutSessionSelectMethodBodyFromJSON,
    CheckoutSessionSelectMethodBodyToJSON,
} from '../models/CheckoutSessionSelectMethodBody';
import {
    type CheckoutSessionSwitchMethod,
    CheckoutSessionSwitchMethodFromJSON,
    CheckoutSessionSwitchMethodToJSON,
} from '../models/CheckoutSessionSwitchMethod';
import {
    type PostCheckoutSessionPublicByIdPay200Response,
    PostCheckoutSessionPublicByIdPay200ResponseFromJSON,
    PostCheckoutSessionPublicByIdPay200ResponseToJSON,
} from '../models/PostCheckoutSessionPublicByIdPay200Response';

export interface GetCheckoutSessionPublicByIdRequest {
    id: string;
}

export interface PostCheckoutSessionRequest {
    checkoutSessionCreateBody: CheckoutSessionCreateBody;
}

export interface PostCheckoutSessionPublicByIdPayRequest {
    id: string;
    checkoutSessionPayBody: CheckoutSessionPayBody;
}

export interface PostCheckoutSessionPublicByIdSwitchMethodRequest {
    id: string;
    checkoutSessionSelectMethodBody: CheckoutSessionSelectMethodBody;
}

/**
 * 
 */
export class CheckoutSessionApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCheckoutSessionPublicById without sending the request
     */
    async getCheckoutSessionPublicByIdRequestOpts(requestParameters: GetCheckoutSessionPublicByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCheckoutSessionPublicById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/checkout-session/public/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get checkout session details without an API key.
     * Get public checkout session
     */
    async getCheckoutSessionPublicByIdRaw(requestParameters: GetCheckoutSessionPublicByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionGet>> {
        const requestOptions = await this.getCheckoutSessionPublicByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionGetFromJSON(jsonValue));
    }

    /**
     * Get checkout session details without an API key.
     * Get public checkout session
     */
    async getCheckoutSessionPublicById(requestParameters: GetCheckoutSessionPublicByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionGet> {
        const response = await this.getCheckoutSessionPublicByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCheckoutSession without sending the request
     */
    async postCheckoutSessionRequestOpts(requestParameters: PostCheckoutSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['checkoutSessionCreateBody'] == null) {
            throw new runtime.RequiredError(
                'checkoutSessionCreateBody',
                'Required parameter "checkoutSessionCreateBody" was null or undefined when calling postCheckoutSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/checkout-session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckoutSessionCreateBodyToJSON(requestParameters['checkoutSessionCreateBody']),
        };
    }

    /**
     * Create a hosted checkout session from paymentRequestId, or from transactionId (optionally creating the payment request when amount is provided).
     * Create checkout session
     */
    async postCheckoutSessionRaw(requestParameters: PostCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionCreate>> {
        const requestOptions = await this.postCheckoutSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionCreateFromJSON(jsonValue));
    }

    /**
     * Create a hosted checkout session from paymentRequestId, or from transactionId (optionally creating the payment request when amount is provided).
     * Create checkout session
     */
    async postCheckoutSession(requestParameters: PostCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionCreate> {
        const response = await this.postCheckoutSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCheckoutSessionPublicByIdPay without sending the request
     */
    async postCheckoutSessionPublicByIdPayRequestOpts(requestParameters: PostCheckoutSessionPublicByIdPayRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling postCheckoutSessionPublicByIdPay().'
            );
        }

        if (requestParameters['checkoutSessionPayBody'] == null) {
            throw new runtime.RequiredError(
                'checkoutSessionPayBody',
                'Required parameter "checkoutSessionPayBody" was null or undefined when calling postCheckoutSessionPublicByIdPay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/checkout-session/public/{id}/pay`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckoutSessionPayBodyToJSON(requestParameters['checkoutSessionPayBody']),
        };
    }

    /**
     * Create payment for a checkout session without requiring API key in the client.
     * Pay public checkout session
     */
    async postCheckoutSessionPublicByIdPayRaw(requestParameters: PostCheckoutSessionPublicByIdPayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostCheckoutSessionPublicByIdPay200Response>> {
        const requestOptions = await this.postCheckoutSessionPublicByIdPayRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostCheckoutSessionPublicByIdPay200ResponseFromJSON(jsonValue));
    }

    /**
     * Create payment for a checkout session without requiring API key in the client.
     * Pay public checkout session
     */
    async postCheckoutSessionPublicByIdPay(requestParameters: PostCheckoutSessionPublicByIdPayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostCheckoutSessionPublicByIdPay200Response> {
        const response = await this.postCheckoutSessionPublicByIdPayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCheckoutSessionPublicByIdSwitchMethod without sending the request
     */
    async postCheckoutSessionPublicByIdSwitchMethodRequestOpts(requestParameters: PostCheckoutSessionPublicByIdSwitchMethodRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling postCheckoutSessionPublicByIdSwitchMethod().'
            );
        }

        if (requestParameters['checkoutSessionSelectMethodBody'] == null) {
            throw new runtime.RequiredError(
                'checkoutSessionSelectMethodBody',
                'Required parameter "checkoutSessionSelectMethodBody" was null or undefined when calling postCheckoutSessionPublicByIdSwitchMethod().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/checkout-session/public/{id}/switch-method`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CheckoutSessionSelectMethodBodyToJSON(requestParameters['checkoutSessionSelectMethodBody']),
        };
    }

    /**
     * Switch checkout method and cancel the latest pending payment when present.
     * Switch public checkout method
     */
    async postCheckoutSessionPublicByIdSwitchMethodRaw(requestParameters: PostCheckoutSessionPublicByIdSwitchMethodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckoutSessionSwitchMethod>> {
        const requestOptions = await this.postCheckoutSessionPublicByIdSwitchMethodRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckoutSessionSwitchMethodFromJSON(jsonValue));
    }

    /**
     * Switch checkout method and cancel the latest pending payment when present.
     * Switch public checkout method
     */
    async postCheckoutSessionPublicByIdSwitchMethod(requestParameters: PostCheckoutSessionPublicByIdSwitchMethodRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckoutSessionSwitchMethod> {
        const response = await this.postCheckoutSessionPublicByIdSwitchMethodRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
