/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ConfigurationGet,
    ConfigurationGetFromJSON,
    ConfigurationGetToJSON,
} from '../models/ConfigurationGet';
import {
    type ConfigurationList,
    ConfigurationListFromJSON,
    ConfigurationListToJSON,
} from '../models/ConfigurationList';

export interface GetConfigurationByIdRequest {
    id: string;
}

/**
 * 
 */
export class ConfigurationApi extends runtime.BaseAPI {

    /**
     * Creates request options for getConfiguration without sending the request
     */
    async getConfigurationRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/configuration`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve all configurations for the current environment
     * List configurations
     */
    async getConfigurationRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigurationList>> {
        const requestOptions = await this.getConfigurationRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigurationListFromJSON(jsonValue));
    }

    /**
     * Retrieve all configurations for the current environment
     * List configurations
     */
    async getConfiguration(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigurationList> {
        const response = await this.getConfigurationRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getConfigurationById without sending the request
     */
    async getConfigurationByIdRequestOpts(requestParameters: GetConfigurationByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getConfigurationById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/configuration/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a specific configuration by ID. Requires secret API key.
     * Get configuration
     */
    async getConfigurationByIdRaw(requestParameters: GetConfigurationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ConfigurationGet>> {
        const requestOptions = await this.getConfigurationByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ConfigurationGetFromJSON(jsonValue));
    }

    /**
     * Retrieve a specific configuration by ID. Requires secret API key.
     * Get configuration
     */
    async getConfigurationById(requestParameters: GetConfigurationByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ConfigurationGet> {
        const response = await this.getConfigurationByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
