/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DeleteConnectRevoke200Response,
    DeleteConnectRevoke200ResponseFromJSON,
    DeleteConnectRevoke200ResponseToJSON,
} from '../models/DeleteConnectRevoke200Response';
import {
    type DeleteConnectRevokeRequest,
    DeleteConnectRevokeRequestFromJSON,
    DeleteConnectRevokeRequestToJSON,
} from '../models/DeleteConnectRevokeRequest';
import {
    type PostConnectExchange200Response,
    PostConnectExchange200ResponseFromJSON,
    PostConnectExchange200ResponseToJSON,
} from '../models/PostConnectExchange200Response';
import {
    type PostConnectExchangeRequest,
    PostConnectExchangeRequestFromJSON,
    PostConnectExchangeRequestToJSON,
} from '../models/PostConnectExchangeRequest';

export interface DeleteConnectRevokeOperationRequest {
    deleteConnectRevokeRequest: DeleteConnectRevokeRequest;
}

export interface PostConnectExchangeOperationRequest {
    postConnectExchangeRequest: PostConnectExchangeRequest;
}

/**
 * 
 */
export class ConnectApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteConnectRevoke without sending the request
     */
    async deleteConnectRevokeRequestOpts(requestParameters: DeleteConnectRevokeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deleteConnectRevokeRequest'] == null) {
            throw new runtime.RequiredError(
                'deleteConnectRevokeRequest',
                'Required parameter "deleteConnectRevokeRequest" was null or undefined when calling deleteConnectRevoke().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/connect/revoke`;

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: DeleteConnectRevokeRequestToJSON(requestParameters['deleteConnectRevokeRequest']),
        };
    }

    /**
     * Revoke a previously authorized connection between a platform and a Moosyl account.
     * Revoke a platform connection
     */
    async deleteConnectRevokeRaw(requestParameters: DeleteConnectRevokeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteConnectRevoke200Response>> {
        const requestOptions = await this.deleteConnectRevokeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteConnectRevoke200ResponseFromJSON(jsonValue));
    }

    /**
     * Revoke a previously authorized connection between a platform and a Moosyl account.
     * Revoke a platform connection
     */
    async deleteConnectRevoke(requestParameters: DeleteConnectRevokeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteConnectRevoke200Response> {
        const response = await this.deleteConnectRevokeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postConnectExchange without sending the request
     */
    async postConnectExchangeRequestOpts(requestParameters: PostConnectExchangeOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postConnectExchangeRequest'] == null) {
            throw new runtime.RequiredError(
                'postConnectExchangeRequest',
                'Required parameter "postConnectExchangeRequest" was null or undefined when calling postConnectExchange().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/connect/exchange`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostConnectExchangeRequestToJSON(requestParameters['postConnectExchangeRequest']),
        };
    }

    /**
     * Exchange a short-lived authorization code (obtained from the /connect flow) for the user\'s publishable key, secret key, and webhook secret. A webhook will be created using the provided endpoints.
     * Exchange authorization code for API credentials
     */
    async postConnectExchangeRaw(requestParameters: PostConnectExchangeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostConnectExchange200Response>> {
        const requestOptions = await this.postConnectExchangeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostConnectExchange200ResponseFromJSON(jsonValue));
    }

    /**
     * Exchange a short-lived authorization code (obtained from the /connect flow) for the user\'s publishable key, secret key, and webhook secret. A webhook will be created using the provided endpoints.
     * Exchange authorization code for API credentials
     */
    async postConnectExchange(requestParameters: PostConnectExchangeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostConnectExchange200Response> {
        const response = await this.postConnectExchangeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
