/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CronResult,
    CronResultFromJSON,
    CronResultToJSON,
} from '../models/CronResult';

/**
 * 
 */
export class CronApi extends runtime.BaseAPI {

    /**
     * Creates request options for postCronBillingCycle without sending the request
     */
    async postCronBillingCycleRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/cron/billing-cycle`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Process billing cycles
     */
    async postCronBillingCycleRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CronResult>> {
        const requestOptions = await this.postCronBillingCycleRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CronResultFromJSON(jsonValue));
    }

    /**
     * Process billing cycles
     */
    async postCronBillingCycle(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CronResult> {
        const response = await this.postCronBillingCycleRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCronExpireSubscriptions without sending the request
     */
    async postCronExpireSubscriptionsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/cron/expire-subscriptions`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Process due cancellations and expirations
     */
    async postCronExpireSubscriptionsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CronResult>> {
        const requestOptions = await this.postCronExpireSubscriptionsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CronResultFromJSON(jsonValue));
    }

    /**
     * Process due cancellations and expirations
     */
    async postCronExpireSubscriptions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CronResult> {
        const response = await this.postCronExpireSubscriptionsRaw(initOverrides);
        return await response.value();
    }

}
