/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CustomerCreate,
    CustomerCreateFromJSON,
    CustomerCreateToJSON,
} from '../models/CustomerCreate';
import {
    type CustomerGet,
    CustomerGetFromJSON,
    CustomerGetToJSON,
} from '../models/CustomerGet';
import {
    type CustomerList,
    CustomerListFromJSON,
    CustomerListToJSON,
} from '../models/CustomerList';
import {
    type CustomerUpdate,
    CustomerUpdateFromJSON,
    CustomerUpdateToJSON,
} from '../models/CustomerUpdate';
import {
    type GetProductsPageParameter,
    GetProductsPageParameterFromJSON,
    GetProductsPageParameterToJSON,
} from '../models/GetProductsPageParameter';

export interface GetCustomersRequest {
    id?: string;
    externalUserId?: string;
    page?: GetProductsPageParameter;
    limit?: GetProductsPageParameter;
}

export interface PatchCustomersByIdRequest {
    id: string;
    customerUpdate: CustomerUpdate;
}

export interface PostCustomersRequest {
    customerCreate: CustomerCreate;
}

/**
 * 
 */
export class CustomersApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCustomers without sending the request
     */
    async getCustomersRequestOpts(requestParameters: GetCustomersRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['externalUserId'] != null) {
            queryParameters['externalUserId'] = requestParameters['externalUserId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/customers/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List customers or filter by id/external user
     */
    async getCustomersRaw(requestParameters: GetCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerList>> {
        const requestOptions = await this.getCustomersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerListFromJSON(jsonValue));
    }

    /**
     * List customers or filter by id/external user
     */
    async getCustomers(requestParameters: GetCustomersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerList> {
        const response = await this.getCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchCustomersById without sending the request
     */
    async patchCustomersByIdRequestOpts(requestParameters: PatchCustomersByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchCustomersById().'
            );
        }

        if (requestParameters['customerUpdate'] == null) {
            throw new runtime.RequiredError(
                'customerUpdate',
                'Required parameter "customerUpdate" was null or undefined when calling patchCustomersById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/customers/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerUpdateToJSON(requestParameters['customerUpdate']),
        };
    }

    /**
     * Update customer
     */
    async patchCustomersByIdRaw(requestParameters: PatchCustomersByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGet>> {
        const requestOptions = await this.patchCustomersByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGetFromJSON(jsonValue));
    }

    /**
     * Update customer
     */
    async patchCustomersById(requestParameters: PatchCustomersByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGet> {
        const response = await this.patchCustomersByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postCustomers without sending the request
     */
    async postCustomersRequestOpts(requestParameters: PostCustomersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['customerCreate'] == null) {
            throw new runtime.RequiredError(
                'customerCreate',
                'Required parameter "customerCreate" was null or undefined when calling postCustomers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/customers/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CustomerCreateToJSON(requestParameters['customerCreate']),
        };
    }

    /**
     * Create customer
     */
    async postCustomersRaw(requestParameters: PostCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerGet>> {
        const requestOptions = await this.postCustomersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerGetFromJSON(jsonValue));
    }

    /**
     * Create customer
     */
    async postCustomers(requestParameters: PostCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerGet> {
        const response = await this.postCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
