/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetProductsPageParameter,
    GetProductsPageParameterFromJSON,
    GetProductsPageParameterToJSON,
} from '../models/GetProductsPageParameter';
import {
    type InvoiceList,
    InvoiceListFromJSON,
    InvoiceListToJSON,
} from '../models/InvoiceList';

export interface GetInvoicesRequest {
    id?: string;
    externalUserId?: string;
    subscriptionId?: string;
    page?: GetProductsPageParameter;
    limit?: GetProductsPageParameter;
}

/**
 * 
 */
export class InvoicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getInvoices without sending the request
     */
    async getInvoicesRequestOpts(requestParameters: GetInvoicesRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['externalUserId'] != null) {
            queryParameters['externalUserId'] = requestParameters['externalUserId'];
        }

        if (requestParameters['subscriptionId'] != null) {
            queryParameters['subscriptionId'] = requestParameters['subscriptionId'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/invoices/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List invoices or filter by id/external user
     */
    async getInvoicesRaw(requestParameters: GetInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceList>> {
        const requestOptions = await this.getInvoicesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceListFromJSON(jsonValue));
    }

    /**
     * List invoices or filter by id/external user
     */
    async getInvoices(requestParameters: GetInvoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceList> {
        const response = await this.getInvoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
