/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PostMasriviInitiate200Response,
    PostMasriviInitiate200ResponseFromJSON,
    PostMasriviInitiate200ResponseToJSON,
} from '../models/PostMasriviInitiate200Response';
import {
    type PostMasriviInitiateRequest,
    PostMasriviInitiateRequestFromJSON,
    PostMasriviInitiateRequestToJSON,
} from '../models/PostMasriviInitiateRequest';

export interface PostMasriviInitiateOperationRequest {
    postMasriviInitiateRequest: PostMasriviInitiateRequest;
}

/**
 * 
 */
export class MasriviApi extends runtime.BaseAPI {

    /**
     * Creates request options for postMasriviInitiate without sending the request
     */
    async postMasriviInitiateRequestOpts(requestParameters: PostMasriviInitiateOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['postMasriviInitiateRequest'] == null) {
            throw new runtime.RequiredError(
                'postMasriviInitiateRequest',
                'Required parameter "postMasriviInitiateRequest" was null or undefined when calling postMasriviInitiate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/masrivi/initiate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostMasriviInitiateRequestToJSON(requestParameters['postMasriviInitiateRequest']),
        };
    }

    /**
     * Creates a pending payment and returns form data to redirect customer to Masrivi payment page.
     * Initiate Masrivi payment
     */
    async postMasriviInitiateRaw(requestParameters: PostMasriviInitiateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostMasriviInitiate200Response>> {
        const requestOptions = await this.postMasriviInitiateRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostMasriviInitiate200ResponseFromJSON(jsonValue));
    }

    /**
     * Creates a pending payment and returns form data to redirect customer to Masrivi payment page.
     * Initiate Masrivi payment
     */
    async postMasriviInitiate(requestParameters: PostMasriviInitiateOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostMasriviInitiate200Response> {
        const response = await this.postMasriviInitiateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
