/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PaymentCreate,
    PaymentCreateFromJSON,
    PaymentCreateToJSON,
} from '../models/PaymentCreate';
import {
    type PaymentGet,
    PaymentGetFromJSON,
    PaymentGetToJSON,
} from '../models/PaymentGet';
import {
    type PostPayment200Response,
    PostPayment200ResponseFromJSON,
    PostPayment200ResponseToJSON,
} from '../models/PostPayment200Response';

export interface GetPaymentByIdRequest {
    id: string;
}

export interface PostPaymentRequest {
    paymentCreate: PaymentCreate;
}

/**
 * 
 */
export class PaymentApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPaymentById without sending the request
     */
    async getPaymentByIdRequestOpts(requestParameters: GetPaymentByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPaymentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/payment/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve detailed information about a payment by transaction ID. Requires secret API key.
     * Get payment details
     */
    async getPaymentByIdRaw(requestParameters: GetPaymentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentGet>> {
        const requestOptions = await this.getPaymentByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentGetFromJSON(jsonValue));
    }

    /**
     * Retrieve detailed information about a payment by transaction ID. Requires secret API key.
     * Get payment details
     */
    async getPaymentById(requestParameters: GetPaymentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentGet> {
        const response = await this.getPaymentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPayment without sending the request
     */
    async postPaymentRequestOpts(requestParameters: PostPaymentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentCreate'] == null) {
            throw new runtime.RequiredError(
                'paymentCreate',
                'Required parameter "paymentCreate" was null or undefined when calling postPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/payment`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentCreateToJSON(requestParameters['paymentCreate']),
        };
    }

    /**
     * Use this endpoint to create a new payment for an existing payment request.  **Testing (Sandbox Environment Only)**  | Phone Number | Status     | |--------------|------------| | 22222222     | Accepted   | | 33333333     | Accepted   | | 44444444     | Accepted   | | Other        | Rejected   |
     * Create a new payment
     */
    async postPaymentRaw(requestParameters: PostPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PostPayment200Response>> {
        const requestOptions = await this.postPaymentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PostPayment200ResponseFromJSON(jsonValue));
    }

    /**
     * Use this endpoint to create a new payment for an existing payment request.  **Testing (Sandbox Environment Only)**  | Phone Number | Status     | |--------------|------------| | 22222222     | Accepted   | | 33333333     | Accepted   | | 44444444     | Accepted   | | Other        | Rejected   |
     * Create a new payment
     */
    async postPayment(requestParameters: PostPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PostPayment200Response> {
        const response = await this.postPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
