/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PaymentRequestCreate,
    PaymentRequestCreateFromJSON,
    PaymentRequestCreateToJSON,
} from '../models/PaymentRequestCreate';
import {
    type PaymentRequestGet,
    PaymentRequestGetFromJSON,
    PaymentRequestGetToJSON,
} from '../models/PaymentRequestGet';
import {
    type PaymentRequestRefreshStatus,
    PaymentRequestRefreshStatusFromJSON,
    PaymentRequestRefreshStatusToJSON,
} from '../models/PaymentRequestRefreshStatus';

export interface GetPaymentRequestByIdRequest {
    id: string;
}

export interface GetPaymentRequestByTransactionByTransactionIdRequest {
    transactionId: string;
}

export interface PatchPaymentRequestByTransactionIdRefreshStatusRequest {
    transactionId: string;
}

export interface PostPaymentRequestRequest {
    paymentRequestCreate: PaymentRequestCreate;
}

/**
 * 
 */
export class PaymentRequestApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPaymentRequestById without sending the request
     */
    async getPaymentRequestByIdRequestOpts(requestParameters: GetPaymentRequestByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPaymentRequestById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/payment-request/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a payment request by ID
     * Get payment request
     */
    async getPaymentRequestByIdRaw(requestParameters: GetPaymentRequestByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentRequestGet>> {
        const requestOptions = await this.getPaymentRequestByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentRequestGetFromJSON(jsonValue));
    }

    /**
     * Retrieve a payment request by ID
     * Get payment request
     */
    async getPaymentRequestById(requestParameters: GetPaymentRequestByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentRequestGet> {
        const response = await this.getPaymentRequestByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPaymentRequestByTransactionByTransactionId without sending the request
     */
    async getPaymentRequestByTransactionByTransactionIdRequestOpts(requestParameters: GetPaymentRequestByTransactionByTransactionIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling getPaymentRequestByTransactionByTransactionId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/payment-request/by-transaction/{transactionId}`;
        urlPath = urlPath.replace('{transactionId}', encodeURIComponent(String(requestParameters['transactionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve a payment request by transaction ID
     * Get payment request by transaction ID
     */
    async getPaymentRequestByTransactionByTransactionIdRaw(requestParameters: GetPaymentRequestByTransactionByTransactionIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentRequestGet>> {
        const requestOptions = await this.getPaymentRequestByTransactionByTransactionIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentRequestGetFromJSON(jsonValue));
    }

    /**
     * Retrieve a payment request by transaction ID
     * Get payment request by transaction ID
     */
    async getPaymentRequestByTransactionByTransactionId(requestParameters: GetPaymentRequestByTransactionByTransactionIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentRequestGet> {
        const response = await this.getPaymentRequestByTransactionByTransactionIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchPaymentRequestByTransactionIdRefreshStatus without sending the request
     */
    async patchPaymentRequestByTransactionIdRefreshStatusRequestOpts(requestParameters: PatchPaymentRequestByTransactionIdRefreshStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['transactionId'] == null) {
            throw new runtime.RequiredError(
                'transactionId',
                'Required parameter "transactionId" was null or undefined when calling patchPaymentRequestByTransactionIdRefreshStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/payment-request/{transactionId}/refresh-status`;
        urlPath = urlPath.replace('{transactionId}', encodeURIComponent(String(requestParameters['transactionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Refresh the status of a payment request by transaction ID. Requires secret API key.
     * Refresh payment request status
     */
    async patchPaymentRequestByTransactionIdRefreshStatusRaw(requestParameters: PatchPaymentRequestByTransactionIdRefreshStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentRequestRefreshStatus>> {
        const requestOptions = await this.patchPaymentRequestByTransactionIdRefreshStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentRequestRefreshStatusFromJSON(jsonValue));
    }

    /**
     * Refresh the status of a payment request by transaction ID. Requires secret API key.
     * Refresh payment request status
     */
    async patchPaymentRequestByTransactionIdRefreshStatus(requestParameters: PatchPaymentRequestByTransactionIdRefreshStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentRequestRefreshStatus> {
        const response = await this.patchPaymentRequestByTransactionIdRefreshStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPaymentRequest without sending the request
     */
    async postPaymentRequestRequestOpts(requestParameters: PostPaymentRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['paymentRequestCreate'] == null) {
            throw new runtime.RequiredError(
                'paymentRequestCreate',
                'Required parameter "paymentRequestCreate" was null or undefined when calling postPaymentRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/payment-request`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentRequestCreateToJSON(requestParameters['paymentRequestCreate']),
        };
    }

    /**
     * Create a new payment request that can be used to collect payments. Requires secret API key.
     * Create payment request
     */
    async postPaymentRequestRaw(requestParameters: PostPaymentRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentRequestGet>> {
        const requestOptions = await this.postPaymentRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentRequestGetFromJSON(jsonValue));
    }

    /**
     * Create a new payment request that can be used to collect payments. Requires secret API key.
     * Create payment request
     */
    async postPaymentRequest(requestParameters: PostPaymentRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentRequestGet> {
        const response = await this.postPaymentRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
