/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PriceCreate,
    PriceCreateFromJSON,
    PriceCreateToJSON,
} from '../models/PriceCreate';
import {
    type PriceGet,
    PriceGetFromJSON,
    PriceGetToJSON,
} from '../models/PriceGet';
import {
    type PriceUpdate,
    PriceUpdateFromJSON,
    PriceUpdateToJSON,
} from '../models/PriceUpdate';
import {
    type Success,
    SuccessFromJSON,
    SuccessToJSON,
} from '../models/Success';

export interface GetPricesByIdRequest {
    id: string;
}

export interface PatchPricesByIdRequest {
    id: string;
    priceUpdate: PriceUpdate;
}

export interface PatchPricesByIdArchiveRequest {
    id: string;
}

export interface PostPricesRequest {
    priceCreate: PriceCreate;
}

/**
 * 
 */
export class PricesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPricesById without sending the request
     */
    async getPricesByIdRequestOpts(requestParameters: GetPricesByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPricesById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/prices/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get price
     */
    async getPricesByIdRaw(requestParameters: GetPricesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceGet>> {
        const requestOptions = await this.getPricesByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceGetFromJSON(jsonValue));
    }

    /**
     * Get price
     */
    async getPricesById(requestParameters: GetPricesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceGet> {
        const response = await this.getPricesByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchPricesById without sending the request
     */
    async patchPricesByIdRequestOpts(requestParameters: PatchPricesByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchPricesById().'
            );
        }

        if (requestParameters['priceUpdate'] == null) {
            throw new runtime.RequiredError(
                'priceUpdate',
                'Required parameter "priceUpdate" was null or undefined when calling patchPricesById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/prices/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PriceUpdateToJSON(requestParameters['priceUpdate']),
        };
    }

    /**
     * Update price
     */
    async patchPricesByIdRaw(requestParameters: PatchPricesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceGet>> {
        const requestOptions = await this.patchPricesByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceGetFromJSON(jsonValue));
    }

    /**
     * Update price
     */
    async patchPricesById(requestParameters: PatchPricesByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceGet> {
        const response = await this.patchPricesByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchPricesByIdArchive without sending the request
     */
    async patchPricesByIdArchiveRequestOpts(requestParameters: PatchPricesByIdArchiveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchPricesByIdArchive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/prices/{id}/archive`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Archive price
     */
    async patchPricesByIdArchiveRaw(requestParameters: PatchPricesByIdArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Success>> {
        const requestOptions = await this.patchPricesByIdArchiveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessFromJSON(jsonValue));
    }

    /**
     * Archive price
     */
    async patchPricesByIdArchive(requestParameters: PatchPricesByIdArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Success> {
        const response = await this.patchPricesByIdArchiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postPrices without sending the request
     */
    async postPricesRequestOpts(requestParameters: PostPricesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['priceCreate'] == null) {
            throw new runtime.RequiredError(
                'priceCreate',
                'Required parameter "priceCreate" was null or undefined when calling postPrices().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/prices/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PriceCreateToJSON(requestParameters['priceCreate']),
        };
    }

    /**
     * Create price
     */
    async postPricesRaw(requestParameters: PostPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceGet>> {
        const requestOptions = await this.postPricesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceGetFromJSON(jsonValue));
    }

    /**
     * Create price
     */
    async postPrices(requestParameters: PostPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceGet> {
        const response = await this.postPricesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
