/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetProductsPageParameter,
    GetProductsPageParameterFromJSON,
    GetProductsPageParameterToJSON,
} from '../models/GetProductsPageParameter';
import {
    type ProductCreate,
    ProductCreateFromJSON,
    ProductCreateToJSON,
} from '../models/ProductCreate';
import {
    type ProductGet,
    ProductGetFromJSON,
    ProductGetToJSON,
} from '../models/ProductGet';
import {
    type ProductGetWithPrices,
    ProductGetWithPricesFromJSON,
    ProductGetWithPricesToJSON,
} from '../models/ProductGetWithPrices';
import {
    type ProductList,
    ProductListFromJSON,
    ProductListToJSON,
} from '../models/ProductList';
import {
    type ProductUpdate,
    ProductUpdateFromJSON,
    ProductUpdateToJSON,
} from '../models/ProductUpdate';
import {
    type Success,
    SuccessFromJSON,
    SuccessToJSON,
} from '../models/Success';

export interface GetProductsRequest {
    id?: string;
    page?: GetProductsPageParameter;
    limit?: GetProductsPageParameter;
}

export interface GetProductsByIdRequest {
    id: string;
}

export interface PatchProductsByIdRequest {
    id: string;
    productUpdate: ProductUpdate;
}

export interface PatchProductsByIdArchiveRequest {
    id: string;
}

export interface PostProductsRequest {
    productCreate: ProductCreate;
}

/**
 * 
 */
export class ProductsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getProducts without sending the request
     */
    async getProductsRequestOpts(requestParameters: GetProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/products/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List products or filter by id
     */
    async getProductsRaw(requestParameters: GetProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductList>> {
        const requestOptions = await this.getProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductListFromJSON(jsonValue));
    }

    /**
     * List products or filter by id
     */
    async getProducts(requestParameters: GetProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductList> {
        const response = await this.getProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getProductsById without sending the request
     */
    async getProductsByIdRequestOpts(requestParameters: GetProductsByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProductsById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/products/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get product with prices
     */
    async getProductsByIdRaw(requestParameters: GetProductsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductGetWithPrices>> {
        const requestOptions = await this.getProductsByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductGetWithPricesFromJSON(jsonValue));
    }

    /**
     * Get product with prices
     */
    async getProductsById(requestParameters: GetProductsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductGetWithPrices> {
        const response = await this.getProductsByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchProductsById without sending the request
     */
    async patchProductsByIdRequestOpts(requestParameters: PatchProductsByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchProductsById().'
            );
        }

        if (requestParameters['productUpdate'] == null) {
            throw new runtime.RequiredError(
                'productUpdate',
                'Required parameter "productUpdate" was null or undefined when calling patchProductsById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/products/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProductUpdateToJSON(requestParameters['productUpdate']),
        };
    }

    /**
     * Update product
     */
    async patchProductsByIdRaw(requestParameters: PatchProductsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductGet>> {
        const requestOptions = await this.patchProductsByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductGetFromJSON(jsonValue));
    }

    /**
     * Update product
     */
    async patchProductsById(requestParameters: PatchProductsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductGet> {
        const response = await this.patchProductsByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchProductsByIdArchive without sending the request
     */
    async patchProductsByIdArchiveRequestOpts(requestParameters: PatchProductsByIdArchiveRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchProductsByIdArchive().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/products/{id}/archive`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Archive product
     */
    async patchProductsByIdArchiveRaw(requestParameters: PatchProductsByIdArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Success>> {
        const requestOptions = await this.patchProductsByIdArchiveRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SuccessFromJSON(jsonValue));
    }

    /**
     * Archive product
     */
    async patchProductsByIdArchive(requestParameters: PatchProductsByIdArchiveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Success> {
        const response = await this.patchProductsByIdArchiveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postProducts without sending the request
     */
    async postProductsRequestOpts(requestParameters: PostProductsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['productCreate'] == null) {
            throw new runtime.RequiredError(
                'productCreate',
                'Required parameter "productCreate" was null or undefined when calling postProducts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/products/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProductCreateToJSON(requestParameters['productCreate']),
        };
    }

    /**
     * Create product
     */
    async postProductsRaw(requestParameters: PostProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductGet>> {
        const requestOptions = await this.postProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductGetFromJSON(jsonValue));
    }

    /**
     * Create product
     */
    async postProducts(requestParameters: PostProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductGet> {
        const response = await this.postProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
