/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type GetProductsPageParameter,
    GetProductsPageParameterFromJSON,
    GetProductsPageParameterToJSON,
} from '../models/GetProductsPageParameter';
import {
    type SubscriptionCreate,
    SubscriptionCreateFromJSON,
    SubscriptionCreateToJSON,
} from '../models/SubscriptionCreate';
import {
    type SubscriptionCreateByExternalUser,
    SubscriptionCreateByExternalUserFromJSON,
    SubscriptionCreateByExternalUserToJSON,
} from '../models/SubscriptionCreateByExternalUser';
import {
    type SubscriptionGet,
    SubscriptionGetFromJSON,
    SubscriptionGetToJSON,
} from '../models/SubscriptionGet';
import {
    type SubscriptionList,
    SubscriptionListFromJSON,
    SubscriptionListToJSON,
} from '../models/SubscriptionList';

export interface GetSubscriptionsRequest {
    status?: GetSubscriptionsStatusEnum;
    page?: GetProductsPageParameter;
    limit?: GetProductsPageParameter;
}

export interface GetSubscriptionsByExternalUserByExternalUserIdRequest {
    externalUserId: string;
}

export interface GetSubscriptionsByIdRequest {
    id: string;
}

export interface PostSubscriptionsRequest {
    subscriptionCreate: SubscriptionCreate;
}

export interface PostSubscriptionsByExternalUserRequest {
    subscriptionCreateByExternalUser: SubscriptionCreateByExternalUser;
}

export interface PostSubscriptionsByIdCancelRequest {
    id: string;
}

/**
 * 
 */
export class SubscriptionsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getSubscriptions without sending the request
     */
    async getSubscriptionsRequestOpts(requestParameters: GetSubscriptionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/subscriptions/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List subscriptions
     */
    async getSubscriptionsRaw(requestParameters: GetSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionList>> {
        const requestOptions = await this.getSubscriptionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionListFromJSON(jsonValue));
    }

    /**
     * List subscriptions
     */
    async getSubscriptions(requestParameters: GetSubscriptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionList> {
        const response = await this.getSubscriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSubscriptionsByExternalUserByExternalUserId without sending the request
     */
    async getSubscriptionsByExternalUserByExternalUserIdRequestOpts(requestParameters: GetSubscriptionsByExternalUserByExternalUserIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['externalUserId'] == null) {
            throw new runtime.RequiredError(
                'externalUserId',
                'Required parameter "externalUserId" was null or undefined when calling getSubscriptionsByExternalUserByExternalUserId().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/subscriptions/by-external-user/{externalUserId}`;
        urlPath = urlPath.replace('{externalUserId}', encodeURIComponent(String(requestParameters['externalUserId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get subscription by external user
     */
    async getSubscriptionsByExternalUserByExternalUserIdRaw(requestParameters: GetSubscriptionsByExternalUserByExternalUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionGet>> {
        const requestOptions = await this.getSubscriptionsByExternalUserByExternalUserIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionGetFromJSON(jsonValue));
    }

    /**
     * Get subscription by external user
     */
    async getSubscriptionsByExternalUserByExternalUserId(requestParameters: GetSubscriptionsByExternalUserByExternalUserIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionGet> {
        const response = await this.getSubscriptionsByExternalUserByExternalUserIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getSubscriptionsById without sending the request
     */
    async getSubscriptionsByIdRequestOpts(requestParameters: GetSubscriptionsByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSubscriptionsById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/subscriptions/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get subscription
     */
    async getSubscriptionsByIdRaw(requestParameters: GetSubscriptionsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionGet>> {
        const requestOptions = await this.getSubscriptionsByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionGetFromJSON(jsonValue));
    }

    /**
     * Get subscription
     */
    async getSubscriptionsById(requestParameters: GetSubscriptionsByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionGet> {
        const response = await this.getSubscriptionsByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSubscriptions without sending the request
     */
    async postSubscriptionsRequestOpts(requestParameters: PostSubscriptionsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['subscriptionCreate'] == null) {
            throw new runtime.RequiredError(
                'subscriptionCreate',
                'Required parameter "subscriptionCreate" was null or undefined when calling postSubscriptions().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/subscriptions/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscriptionCreateToJSON(requestParameters['subscriptionCreate']),
        };
    }

    /**
     * Create subscription
     */
    async postSubscriptionsRaw(requestParameters: PostSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionGet>> {
        const requestOptions = await this.postSubscriptionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionGetFromJSON(jsonValue));
    }

    /**
     * Create subscription
     */
    async postSubscriptions(requestParameters: PostSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionGet> {
        const response = await this.postSubscriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSubscriptionsByExternalUser without sending the request
     */
    async postSubscriptionsByExternalUserRequestOpts(requestParameters: PostSubscriptionsByExternalUserRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['subscriptionCreateByExternalUser'] == null) {
            throw new runtime.RequiredError(
                'subscriptionCreateByExternalUser',
                'Required parameter "subscriptionCreateByExternalUser" was null or undefined when calling postSubscriptionsByExternalUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/subscriptions/by-external-user`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SubscriptionCreateByExternalUserToJSON(requestParameters['subscriptionCreateByExternalUser']),
        };
    }

    /**
     * Create subscription by external user
     */
    async postSubscriptionsByExternalUserRaw(requestParameters: PostSubscriptionsByExternalUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionGet>> {
        const requestOptions = await this.postSubscriptionsByExternalUserRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionGetFromJSON(jsonValue));
    }

    /**
     * Create subscription by external user
     */
    async postSubscriptionsByExternalUser(requestParameters: PostSubscriptionsByExternalUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionGet> {
        const response = await this.postSubscriptionsByExternalUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for postSubscriptionsByIdCancel without sending the request
     */
    async postSubscriptionsByIdCancelRequestOpts(requestParameters: PostSubscriptionsByIdCancelRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling postSubscriptionsByIdCancel().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKey authentication
        }


        let urlPath = `/subscriptions/{id}/cancel`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel subscription
     */
    async postSubscriptionsByIdCancelRaw(requestParameters: PostSubscriptionsByIdCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubscriptionGet>> {
        const requestOptions = await this.postSubscriptionsByIdCancelRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SubscriptionGetFromJSON(jsonValue));
    }

    /**
     * Cancel subscription
     */
    async postSubscriptionsByIdCancel(requestParameters: PostSubscriptionsByIdCancelRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubscriptionGet> {
        const response = await this.postSubscriptionsByIdCancelRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetSubscriptionsStatusEnum = {
    Trialing: 'trialing',
    Active: 'active',
    PastDue: 'past_due',
    Paused: 'paused',
    Cancelled: 'cancelled',
    Expired: 'expired',
    PendingCancellation: 'pending_cancellation'
} as const;
export type GetSubscriptionsStatusEnum = typeof GetSubscriptionsStatusEnum[keyof typeof GetSubscriptionsStatusEnum];
