/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckoutSessionCreateData } from './CheckoutSessionCreateData';
import {
    CheckoutSessionCreateDataFromJSON,
    CheckoutSessionCreateDataFromJSONTyped,
    CheckoutSessionCreateDataToJSON,
    CheckoutSessionCreateDataToJSONTyped,
} from './CheckoutSessionCreateData';
import type { PaymentRequestGetData } from './PaymentRequestGetData';
import {
    PaymentRequestGetDataFromJSON,
    PaymentRequestGetDataFromJSONTyped,
    PaymentRequestGetDataToJSON,
    PaymentRequestGetDataToJSONTyped,
} from './PaymentRequestGetData';
import type { GetOrganizationById200ResponseData } from './GetOrganizationById200ResponseData';
import {
    GetOrganizationById200ResponseDataFromJSON,
    GetOrganizationById200ResponseDataFromJSONTyped,
    GetOrganizationById200ResponseDataToJSON,
    GetOrganizationById200ResponseDataToJSONTyped,
} from './GetOrganizationById200ResponseData';
import type { CheckoutSessionGetLatestPayment } from './CheckoutSessionGetLatestPayment';
import {
    CheckoutSessionGetLatestPaymentFromJSON,
    CheckoutSessionGetLatestPaymentFromJSONTyped,
    CheckoutSessionGetLatestPaymentToJSON,
    CheckoutSessionGetLatestPaymentToJSONTyped,
} from './CheckoutSessionGetLatestPayment';
import type { ConfigurationListDataInner } from './ConfigurationListDataInner';
import {
    ConfigurationListDataInnerFromJSON,
    ConfigurationListDataInnerFromJSONTyped,
    ConfigurationListDataInnerToJSON,
    ConfigurationListDataInnerToJSONTyped,
} from './ConfigurationListDataInner';

/**
 * 
 * @export
 * @interface CheckoutSessionSwitchMethod
 */
export interface CheckoutSessionSwitchMethod {
    /**
     * 
     * @type {CheckoutSessionCreateData}
     * @memberof CheckoutSessionSwitchMethod
     */
    data: CheckoutSessionCreateData;
    /**
     * 
     * @type {GetOrganizationById200ResponseData}
     * @memberof CheckoutSessionSwitchMethod
     */
    organization: GetOrganizationById200ResponseData;
    /**
     * 
     * @type {PaymentRequestGetData}
     * @memberof CheckoutSessionSwitchMethod
     */
    paymentRequest: PaymentRequestGetData;
    /**
     * 
     * @type {Array<ConfigurationListDataInner>}
     * @memberof CheckoutSessionSwitchMethod
     */
    configurations: Array<ConfigurationListDataInner>;
    /**
     * 
     * @type {CheckoutSessionGetLatestPayment}
     * @memberof CheckoutSessionSwitchMethod
     */
    latestPayment?: CheckoutSessionGetLatestPayment;
}

/**
 * Check if a given object implements the CheckoutSessionSwitchMethod interface.
 */
export function instanceOfCheckoutSessionSwitchMethod(value: object): value is CheckoutSessionSwitchMethod {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('paymentRequest' in value) || value['paymentRequest'] === undefined) return false;
    if (!('configurations' in value) || value['configurations'] === undefined) return false;
    return true;
}

export function CheckoutSessionSwitchMethodFromJSON(json: any): CheckoutSessionSwitchMethod {
    return CheckoutSessionSwitchMethodFromJSONTyped(json, false);
}

export function CheckoutSessionSwitchMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionSwitchMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CheckoutSessionCreateDataFromJSON(json['data']),
        'organization': GetOrganizationById200ResponseDataFromJSON(json['organization']),
        'paymentRequest': PaymentRequestGetDataFromJSON(json['paymentRequest']),
        'configurations': ((json['configurations'] as Array<any>).map(ConfigurationListDataInnerFromJSON)),
        'latestPayment': json['latestPayment'] == null ? undefined : CheckoutSessionGetLatestPaymentFromJSON(json['latestPayment']),
    };
}

export function CheckoutSessionSwitchMethodToJSON(json: any): CheckoutSessionSwitchMethod {
    return CheckoutSessionSwitchMethodToJSONTyped(json, false);
}

export function CheckoutSessionSwitchMethodToJSONTyped(value?: CheckoutSessionSwitchMethod | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CheckoutSessionCreateDataToJSON(value['data']),
        'organization': GetOrganizationById200ResponseDataToJSON(value['organization']),
        'paymentRequest': PaymentRequestGetDataToJSON(value['paymentRequest']),
        'configurations': ((value['configurations'] as Array<any>).map(ConfigurationListDataInnerToJSON)),
        'latestPayment': CheckoutSessionGetLatestPaymentToJSON(value['latestPayment']),
    };
}

