/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProductsPageParameter } from './GetProductsPageParameter';
import {
    GetProductsPageParameterFromJSON,
    GetProductsPageParameterFromJSONTyped,
    GetProductsPageParameterToJSON,
    GetProductsPageParameterToJSONTyped,
} from './GetProductsPageParameter';

/**
 * 
 * @export
 * @interface CheckoutSessionCreateBody
 */
export interface CheckoutSessionCreateBody {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateBody
     */
    paymentRequestId?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateBody
     */
    transactionId?: string;
    /**
     * 
     * @type {GetProductsPageParameter}
     * @memberof CheckoutSessionCreateBody
     */
    amount?: GetProductsPageParameter;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateBody
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateBody
     */
    successUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateBody
     */
    cancelUrl?: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutSessionCreateBody
     */
    expiresInMinutes?: number;
}

/**
 * Check if a given object implements the CheckoutSessionCreateBody interface.
 */
export function instanceOfCheckoutSessionCreateBody(value: object): value is CheckoutSessionCreateBody {
    return true;
}

export function CheckoutSessionCreateBodyFromJSON(json: any): CheckoutSessionCreateBody {
    return CheckoutSessionCreateBodyFromJSONTyped(json, false);
}

export function CheckoutSessionCreateBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionCreateBody {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentRequestId': json['paymentRequestId'] == null ? undefined : json['paymentRequestId'],
        'transactionId': json['transactionId'] == null ? undefined : json['transactionId'],
        'amount': json['amount'] == null ? undefined : GetProductsPageParameterFromJSON(json['amount']),
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'successUrl': json['successUrl'] == null ? undefined : json['successUrl'],
        'cancelUrl': json['cancelUrl'] == null ? undefined : json['cancelUrl'],
        'expiresInMinutes': json['expiresInMinutes'] == null ? undefined : json['expiresInMinutes'],
    };
}

export function CheckoutSessionCreateBodyToJSON(json: any): CheckoutSessionCreateBody {
    return CheckoutSessionCreateBodyToJSONTyped(json, false);
}

export function CheckoutSessionCreateBodyToJSONTyped(value?: CheckoutSessionCreateBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentRequestId': value['paymentRequestId'],
        'transactionId': value['transactionId'],
        'amount': GetProductsPageParameterToJSON(value['amount']),
        'phoneNumber': value['phoneNumber'],
        'successUrl': value['successUrl'],
        'cancelUrl': value['cancelUrl'],
        'expiresInMinutes': value['expiresInMinutes'],
    };
}

