/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionSelectMethodBody
 */
export interface CheckoutSessionSelectMethodBody {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionSelectMethodBody
     */
    configurationId: string;
}

/**
 * Check if a given object implements the CheckoutSessionSelectMethodBody interface.
 */
export function instanceOfCheckoutSessionSelectMethodBody(value: object): value is CheckoutSessionSelectMethodBody {
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    return true;
}

export function CheckoutSessionSelectMethodBodyFromJSON(json: any): CheckoutSessionSelectMethodBody {
    return CheckoutSessionSelectMethodBodyFromJSONTyped(json, false);
}

export function CheckoutSessionSelectMethodBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionSelectMethodBody {
    if (json == null) {
        return json;
    }
    return {
        
        'configurationId': json['configurationId'],
    };
}

export function CheckoutSessionSelectMethodBodyToJSON(json: any): CheckoutSessionSelectMethodBody {
    return CheckoutSessionSelectMethodBodyToJSONTyped(json, false);
}

export function CheckoutSessionSelectMethodBodyToJSONTyped(value?: CheckoutSessionSelectMethodBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configurationId': value['configurationId'],
    };
}

