/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionCreateData
 */
export interface CheckoutSessionCreateData {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateData
     */
    paymentRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateData
     */
    environmentId: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateData
     */
    selectedConfigurationId: string | null;
    /**
     * 
     * @type {CheckoutSessionCreateDataStatusEnum}
     * @memberof CheckoutSessionCreateData
     */
    status: CheckoutSessionCreateDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateData
     */
    successUrl: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreateData
     */
    cancelUrl: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionCreateData
     */
    expiresAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionCreateData
     */
    completedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionCreateData
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof CheckoutSessionCreateData
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const CheckoutSessionCreateDataStatusEnum = {
    Open: 'open',
    Completed: 'completed',
    Expired: 'expired',
    Cancelled: 'cancelled'
} as const;
export type CheckoutSessionCreateDataStatusEnum = typeof CheckoutSessionCreateDataStatusEnum[keyof typeof CheckoutSessionCreateDataStatusEnum];


/**
 * Check if a given object implements the CheckoutSessionCreateData interface.
 */
export function instanceOfCheckoutSessionCreateData(value: object): value is CheckoutSessionCreateData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('paymentRequestId' in value) || value['paymentRequestId'] === undefined) return false;
    if (!('environmentId' in value) || value['environmentId'] === undefined) return false;
    if (!('selectedConfigurationId' in value) || value['selectedConfigurationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    if (!('cancelUrl' in value) || value['cancelUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function CheckoutSessionCreateDataFromJSON(json: any): CheckoutSessionCreateData {
    return CheckoutSessionCreateDataFromJSONTyped(json, false);
}

export function CheckoutSessionCreateDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionCreateData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'paymentRequestId': json['paymentRequestId'],
        'environmentId': json['environmentId'],
        'selectedConfigurationId': json['selectedConfigurationId'],
        'status': json['status'],
        'successUrl': json['successUrl'],
        'cancelUrl': json['cancelUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
        'completedAt': (json['completedAt'] == null ? null : new Date(json['completedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function CheckoutSessionCreateDataToJSON(json: any): CheckoutSessionCreateData {
    return CheckoutSessionCreateDataToJSONTyped(json, false);
}

export function CheckoutSessionCreateDataToJSONTyped(value?: CheckoutSessionCreateData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'paymentRequestId': value['paymentRequestId'],
        'environmentId': value['environmentId'],
        'selectedConfigurationId': value['selectedConfigurationId'],
        'status': value['status'],
        'successUrl': value['successUrl'],
        'cancelUrl': value['cancelUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

