/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckoutSessionCreateData } from './CheckoutSessionCreateData';
import {
    CheckoutSessionCreateDataFromJSON,
    CheckoutSessionCreateDataFromJSONTyped,
    CheckoutSessionCreateDataToJSON,
    CheckoutSessionCreateDataToJSONTyped,
} from './CheckoutSessionCreateData';

/**
 * 
 * @export
 * @interface CheckoutSessionCreate
 */
export interface CheckoutSessionCreate {
    /**
     * 
     * @type {CheckoutSessionCreateData}
     * @memberof CheckoutSessionCreate
     */
    data: CheckoutSessionCreateData;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionCreate
     */
    checkoutUrl: string;
}

/**
 * Check if a given object implements the CheckoutSessionCreate interface.
 */
export function instanceOfCheckoutSessionCreate(value: object): value is CheckoutSessionCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('checkoutUrl' in value) || value['checkoutUrl'] === undefined) return false;
    return true;
}

export function CheckoutSessionCreateFromJSON(json: any): CheckoutSessionCreate {
    return CheckoutSessionCreateFromJSONTyped(json, false);
}

export function CheckoutSessionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CheckoutSessionCreateDataFromJSON(json['data']),
        'checkoutUrl': json['checkoutUrl'],
    };
}

export function CheckoutSessionCreateToJSON(json: any): CheckoutSessionCreate {
    return CheckoutSessionCreateToJSONTyped(json, false);
}

export function CheckoutSessionCreateToJSONTyped(value?: CheckoutSessionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CheckoutSessionCreateDataToJSON(value['data']),
        'checkoutUrl': value['checkoutUrl'],
    };
}

