/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CheckoutSessionCreateData } from './CheckoutSessionCreateData';
import {
    CheckoutSessionCreateDataFromJSON,
    CheckoutSessionCreateDataFromJSONTyped,
    CheckoutSessionCreateDataToJSON,
    CheckoutSessionCreateDataToJSONTyped,
} from './CheckoutSessionCreateData';
import type { PaymentRequestGetData } from './PaymentRequestGetData';
import {
    PaymentRequestGetDataFromJSON,
    PaymentRequestGetDataFromJSONTyped,
    PaymentRequestGetDataToJSON,
    PaymentRequestGetDataToJSONTyped,
} from './PaymentRequestGetData';
import type { GetOrganizationById200ResponseData } from './GetOrganizationById200ResponseData';
import {
    GetOrganizationById200ResponseDataFromJSON,
    GetOrganizationById200ResponseDataFromJSONTyped,
    GetOrganizationById200ResponseDataToJSON,
    GetOrganizationById200ResponseDataToJSONTyped,
} from './GetOrganizationById200ResponseData';
import type { CheckoutSessionGetLatestPayment } from './CheckoutSessionGetLatestPayment';
import {
    CheckoutSessionGetLatestPaymentFromJSON,
    CheckoutSessionGetLatestPaymentFromJSONTyped,
    CheckoutSessionGetLatestPaymentToJSON,
    CheckoutSessionGetLatestPaymentToJSONTyped,
} from './CheckoutSessionGetLatestPayment';
import type { ConfigurationListDataInner } from './ConfigurationListDataInner';
import {
    ConfigurationListDataInnerFromJSON,
    ConfigurationListDataInnerFromJSONTyped,
    ConfigurationListDataInnerToJSON,
    ConfigurationListDataInnerToJSONTyped,
} from './ConfigurationListDataInner';

/**
 * 
 * @export
 * @interface CheckoutSessionGet
 */
export interface CheckoutSessionGet {
    /**
     * 
     * @type {CheckoutSessionCreateData}
     * @memberof CheckoutSessionGet
     */
    data: CheckoutSessionCreateData;
    /**
     * 
     * @type {GetOrganizationById200ResponseData}
     * @memberof CheckoutSessionGet
     */
    organization: GetOrganizationById200ResponseData;
    /**
     * 
     * @type {PaymentRequestGetData}
     * @memberof CheckoutSessionGet
     */
    paymentRequest: PaymentRequestGetData;
    /**
     * 
     * @type {Array<ConfigurationListDataInner>}
     * @memberof CheckoutSessionGet
     */
    configurations: Array<ConfigurationListDataInner>;
    /**
     * 
     * @type {CheckoutSessionGetLatestPayment}
     * @memberof CheckoutSessionGet
     */
    latestPayment?: CheckoutSessionGetLatestPayment;
}

/**
 * Check if a given object implements the CheckoutSessionGet interface.
 */
export function instanceOfCheckoutSessionGet(value: object): value is CheckoutSessionGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    if (!('paymentRequest' in value) || value['paymentRequest'] === undefined) return false;
    if (!('configurations' in value) || value['configurations'] === undefined) return false;
    return true;
}

export function CheckoutSessionGetFromJSON(json: any): CheckoutSessionGet {
    return CheckoutSessionGetFromJSONTyped(json, false);
}

export function CheckoutSessionGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CheckoutSessionCreateDataFromJSON(json['data']),
        'organization': GetOrganizationById200ResponseDataFromJSON(json['organization']),
        'paymentRequest': PaymentRequestGetDataFromJSON(json['paymentRequest']),
        'configurations': ((json['configurations'] as Array<any>).map(ConfigurationListDataInnerFromJSON)),
        'latestPayment': json['latestPayment'] == null ? undefined : CheckoutSessionGetLatestPaymentFromJSON(json['latestPayment']),
    };
}

export function CheckoutSessionGetToJSON(json: any): CheckoutSessionGet {
    return CheckoutSessionGetToJSONTyped(json, false);
}

export function CheckoutSessionGetToJSONTyped(value?: CheckoutSessionGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CheckoutSessionCreateDataToJSON(value['data']),
        'organization': GetOrganizationById200ResponseDataToJSON(value['organization']),
        'paymentRequest': PaymentRequestGetDataToJSON(value['paymentRequest']),
        'configurations': ((value['configurations'] as Array<any>).map(ConfigurationListDataInnerToJSON)),
        'latestPayment': CheckoutSessionGetLatestPaymentToJSON(value['latestPayment']),
    };
}

