/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionPayBody
 */
export interface CheckoutSessionPayBody {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionPayBody
     */
    configurationId: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionPayBody
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionPayBody
     */
    passCode?: string;
}

/**
 * Check if a given object implements the CheckoutSessionPayBody interface.
 */
export function instanceOfCheckoutSessionPayBody(value: object): value is CheckoutSessionPayBody {
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    return true;
}

export function CheckoutSessionPayBodyFromJSON(json: any): CheckoutSessionPayBody {
    return CheckoutSessionPayBodyFromJSONTyped(json, false);
}

export function CheckoutSessionPayBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionPayBody {
    if (json == null) {
        return json;
    }
    return {
        
        'configurationId': json['configurationId'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'passCode': json['passCode'] == null ? undefined : json['passCode'],
    };
}

export function CheckoutSessionPayBodyToJSON(json: any): CheckoutSessionPayBody {
    return CheckoutSessionPayBodyToJSONTyped(json, false);
}

export function CheckoutSessionPayBodyToJSONTyped(value?: CheckoutSessionPayBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configurationId': value['configurationId'],
        'phoneNumber': value['phoneNumber'],
        'passCode': value['passCode'],
    };
}

