/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckoutSessionGetLatestPayment
 */
export interface CheckoutSessionGetLatestPayment {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionGetLatestPayment
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof CheckoutSessionGetLatestPayment
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionGetLatestPayment
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionGetLatestPayment
     */
    referenceId: string | null;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSessionGetLatestPayment
     */
    paymentCode?: string;
}

/**
 * Check if a given object implements the CheckoutSessionGetLatestPayment interface.
 */
export function instanceOfCheckoutSessionGetLatestPayment(value: object): value is CheckoutSessionGetLatestPayment {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('referenceId' in value) || value['referenceId'] === undefined) return false;
    return true;
}

export function CheckoutSessionGetLatestPaymentFromJSON(json: any): CheckoutSessionGetLatestPayment {
    return CheckoutSessionGetLatestPaymentFromJSONTyped(json, false);
}

export function CheckoutSessionGetLatestPaymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckoutSessionGetLatestPayment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'status': json['status'],
        'referenceId': json['referenceId'],
        'paymentCode': json['paymentCode'] == null ? undefined : json['paymentCode'],
    };
}

export function CheckoutSessionGetLatestPaymentToJSON(json: any): CheckoutSessionGetLatestPayment {
    return CheckoutSessionGetLatestPaymentToJSONTyped(json, false);
}

export function CheckoutSessionGetLatestPaymentToJSONTyped(value?: CheckoutSessionGetLatestPayment | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'status': value['status'],
        'referenceId': value['referenceId'],
        'paymentCode': value['paymentCode'],
    };
}

