/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigurationGetData
 */
export interface ConfigurationGetData {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationGetData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationGetData
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationGetData
     */
    organizationId: string | null;
    /**
     * 
     * @type {any}
     * @memberof ConfigurationGetData
     */
    config: any | null;
    /**
     * 
     * @type {Date}
     * @memberof ConfigurationGetData
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ConfigurationGetData
     */
    updatedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigurationGetData
     */
    isTestingMode: boolean;
}

/**
 * Check if a given object implements the ConfigurationGetData interface.
 */
export function instanceOfConfigurationGetData(value: object): value is ConfigurationGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('isTestingMode' in value) || value['isTestingMode'] === undefined) return false;
    return true;
}

export function ConfigurationGetDataFromJSON(json: any): ConfigurationGetData {
    return ConfigurationGetDataFromJSONTyped(json, false);
}

export function ConfigurationGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'organizationId': json['organizationId'],
        'config': json['config'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
        'isTestingMode': json['isTestingMode'],
    };
}

export function ConfigurationGetDataToJSON(json: any): ConfigurationGetData {
    return ConfigurationGetDataToJSONTyped(json, false);
}

export function ConfigurationGetDataToJSONTyped(value?: ConfigurationGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'organizationId': value['organizationId'],
        'config': value['config'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
        'isTestingMode': value['isTestingMode'],
    };
}

