/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigurationGetData } from './ConfigurationGetData';
import {
    ConfigurationGetDataFromJSON,
    ConfigurationGetDataFromJSONTyped,
    ConfigurationGetDataToJSON,
    ConfigurationGetDataToJSONTyped,
} from './ConfigurationGetData';

/**
 * 
 * @export
 * @interface ConfigurationGet
 */
export interface ConfigurationGet {
    /**
     * 
     * @type {ConfigurationGetData}
     * @memberof ConfigurationGet
     */
    data: ConfigurationGetData;
}

/**
 * Check if a given object implements the ConfigurationGet interface.
 */
export function instanceOfConfigurationGet(value: object): value is ConfigurationGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ConfigurationGetFromJSON(json: any): ConfigurationGet {
    return ConfigurationGetFromJSONTyped(json, false);
}

export function ConfigurationGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ConfigurationGetDataFromJSON(json['data']),
    };
}

export function ConfigurationGetToJSON(json: any): ConfigurationGet {
    return ConfigurationGetToJSONTyped(json, false);
}

export function ConfigurationGetToJSONTyped(value?: ConfigurationGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ConfigurationGetDataToJSON(value['data']),
    };
}

