/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigurationListDataInner } from './ConfigurationListDataInner';
import {
    ConfigurationListDataInnerFromJSON,
    ConfigurationListDataInnerFromJSONTyped,
    ConfigurationListDataInnerToJSON,
    ConfigurationListDataInnerToJSONTyped,
} from './ConfigurationListDataInner';

/**
 * 
 * @export
 * @interface ConfigurationList
 */
export interface ConfigurationList {
    /**
     * 
     * @type {Array<ConfigurationListDataInner>}
     * @memberof ConfigurationList
     */
    data: Array<ConfigurationListDataInner>;
}

/**
 * Check if a given object implements the ConfigurationList interface.
 */
export function instanceOfConfigurationList(value: object): value is ConfigurationList {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ConfigurationListFromJSON(json: any): ConfigurationList {
    return ConfigurationListFromJSONTyped(json, false);
}

export function ConfigurationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ConfigurationListDataInnerFromJSON)),
    };
}

export function ConfigurationListToJSON(json: any): ConfigurationList {
    return ConfigurationListToJSONTyped(json, false);
}

export function ConfigurationListToJSONTyped(value?: ConfigurationList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ConfigurationListDataInnerToJSON)),
    };
}

