/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfigurationListDataInner
 */
export interface ConfigurationListDataInner {
    /**
     * 
     * @type {string}
     * @memberof ConfigurationListDataInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationListDataInner
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationListDataInner
     */
    organizationId: string | null;
    /**
     * 
     * @type {any}
     * @memberof ConfigurationListDataInner
     */
    config: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigurationListDataInner
     */
    isTestingMode: boolean;
}

/**
 * Check if a given object implements the ConfigurationListDataInner interface.
 */
export function instanceOfConfigurationListDataInner(value: object): value is ConfigurationListDataInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    if (!('isTestingMode' in value) || value['isTestingMode'] === undefined) return false;
    return true;
}

export function ConfigurationListDataInnerFromJSON(json: any): ConfigurationListDataInner {
    return ConfigurationListDataInnerFromJSONTyped(json, false);
}

export function ConfigurationListDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationListDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'organizationId': json['organizationId'],
        'config': json['config'],
        'isTestingMode': json['isTestingMode'],
    };
}

export function ConfigurationListDataInnerToJSON(json: any): ConfigurationListDataInner {
    return ConfigurationListDataInnerToJSONTyped(json, false);
}

export function ConfigurationListDataInnerToJSONTyped(value?: ConfigurationListDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'organizationId': value['organizationId'],
        'config': value['config'],
        'isTestingMode': value['isTestingMode'],
    };
}

