/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConfigurationCreateData } from './ConfigurationCreateData';
import {
    ConfigurationCreateDataFromJSON,
    ConfigurationCreateDataFromJSONTyped,
    ConfigurationCreateDataToJSON,
    ConfigurationCreateDataToJSONTyped,
} from './ConfigurationCreateData';

/**
 * 
 * @export
 * @interface ConfigurationCreate
 */
export interface ConfigurationCreate {
    /**
     * 
     * @type {ConfigurationCreateData}
     * @memberof ConfigurationCreate
     */
    data: ConfigurationCreateData;
}

/**
 * Check if a given object implements the ConfigurationCreate interface.
 */
export function instanceOfConfigurationCreate(value: object): value is ConfigurationCreate {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ConfigurationCreateFromJSON(json: any): ConfigurationCreate {
    return ConfigurationCreateFromJSONTyped(json, false);
}

export function ConfigurationCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ConfigurationCreateDataFromJSON(json['data']),
    };
}

export function ConfigurationCreateToJSON(json: any): ConfigurationCreate {
    return ConfigurationCreateToJSONTyped(json, false);
}

export function ConfigurationCreateToJSONTyped(value?: ConfigurationCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ConfigurationCreateDataToJSON(value['data']),
    };
}

