/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CronResult
 */
export interface CronResult {
    /**
     * 
     * @type {number}
     * @memberof CronResult
     */
    cancelled?: number;
    /**
     * 
     * @type {number}
     * @memberof CronResult
     */
    expired?: number;
    /**
     * 
     * @type {number}
     * @memberof CronResult
     */
    updated?: number;
    /**
     * 
     * @type {number}
     * @memberof CronResult
     */
    processed?: number;
    /**
     * 
     * @type {number}
     * @memberof CronResult
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof CronResult
     */
    total?: number;
    /**
     * 
     * @type {string}
     * @memberof CronResult
     */
    processedAt: string;
}

/**
 * Check if a given object implements the CronResult interface.
 */
export function instanceOfCronResult(value: object): value is CronResult {
    if (!('processedAt' in value) || value['processedAt'] === undefined) return false;
    return true;
}

export function CronResultFromJSON(json: any): CronResult {
    return CronResultFromJSONTyped(json, false);
}

export function CronResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CronResult {
    if (json == null) {
        return json;
    }
    return {
        
        'cancelled': json['cancelled'] == null ? undefined : json['cancelled'],
        'expired': json['expired'] == null ? undefined : json['expired'],
        'updated': json['updated'] == null ? undefined : json['updated'],
        'processed': json['processed'] == null ? undefined : json['processed'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'total': json['total'] == null ? undefined : json['total'],
        'processedAt': json['processedAt'],
    };
}

export function CronResultToJSON(json: any): CronResult {
    return CronResultToJSONTyped(json, false);
}

export function CronResultToJSONTyped(value?: CronResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelled': value['cancelled'],
        'expired': value['expired'],
        'updated': value['updated'],
        'processed': value['processed'],
        'failed': value['failed'],
        'total': value['total'],
        'processedAt': value['processedAt'],
    };
}

