/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerGetData } from './CustomerGetData';
import {
    CustomerGetDataFromJSON,
    CustomerGetDataFromJSONTyped,
    CustomerGetDataToJSON,
    CustomerGetDataToJSONTyped,
} from './CustomerGetData';

/**
 * 
 * @export
 * @interface CustomerGet
 */
export interface CustomerGet {
    /**
     * 
     * @type {CustomerGetData}
     * @memberof CustomerGet
     */
    data: CustomerGetData;
}

/**
 * Check if a given object implements the CustomerGet interface.
 */
export function instanceOfCustomerGet(value: object): value is CustomerGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CustomerGetFromJSON(json: any): CustomerGet {
    return CustomerGetFromJSONTyped(json, false);
}

export function CustomerGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CustomerGetDataFromJSON(json['data']),
    };
}

export function CustomerGetToJSON(json: any): CustomerGet {
    return CustomerGetToJSONTyped(json, false);
}

export function CustomerGetToJSONTyped(value?: CustomerGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': CustomerGetDataToJSON(value['data']),
    };
}

