/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerUpdate
 */
export interface CustomerUpdate {
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdate
     */
    externalUserId?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerUpdate
     */
    phone?: string | null;
}

/**
 * Check if a given object implements the CustomerUpdate interface.
 */
export function instanceOfCustomerUpdate(value: object): value is CustomerUpdate {
    return true;
}

export function CustomerUpdateFromJSON(json: any): CustomerUpdate {
    return CustomerUpdateFromJSONTyped(json, false);
}

export function CustomerUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'externalUserId': json['externalUserId'] == null ? undefined : json['externalUserId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function CustomerUpdateToJSON(json: any): CustomerUpdate {
    return CustomerUpdateToJSONTyped(json, false);
}

export function CustomerUpdateToJSONTyped(value?: CustomerUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalUserId': value['externalUserId'],
        'phone': value['phone'],
    };
}

