/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerGetData
 */
export interface CustomerGetData {
    /**
     * 
     * @type {string}
     * @memberof CustomerGetData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGetData
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGetData
     */
    externalUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerGetData
     */
    phone: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CustomerGetData
     */
    createdAt: Date | null;
}

/**
 * Check if a given object implements the CustomerGetData interface.
 */
export function instanceOfCustomerGetData(value: object): value is CustomerGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('externalUserId' in value) || value['externalUserId'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CustomerGetDataFromJSON(json: any): CustomerGetData {
    return CustomerGetDataFromJSONTyped(json, false);
}

export function CustomerGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'externalUserId': json['externalUserId'],
        'phone': json['phone'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
    };
}

export function CustomerGetDataToJSON(json: any): CustomerGetData {
    return CustomerGetDataToJSONTyped(json, false);
}

export function CustomerGetDataToJSONTyped(value?: CustomerGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'externalUserId': value['externalUserId'],
        'phone': value['phone'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

