/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerGetData } from './CustomerGetData';
import {
    CustomerGetDataFromJSON,
    CustomerGetDataFromJSONTyped,
    CustomerGetDataToJSON,
    CustomerGetDataToJSONTyped,
} from './CustomerGetData';
import type { ProductListPagination } from './ProductListPagination';
import {
    ProductListPaginationFromJSON,
    ProductListPaginationFromJSONTyped,
    ProductListPaginationToJSON,
    ProductListPaginationToJSONTyped,
} from './ProductListPagination';

/**
 * 
 * @export
 * @interface CustomerList
 */
export interface CustomerList {
    /**
     * 
     * @type {Array<CustomerGetData>}
     * @memberof CustomerList
     */
    data: Array<CustomerGetData>;
    /**
     * 
     * @type {ProductListPagination}
     * @memberof CustomerList
     */
    pagination: ProductListPagination;
}

/**
 * Check if a given object implements the CustomerList interface.
 */
export function instanceOfCustomerList(value: object): value is CustomerList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function CustomerListFromJSON(json: any): CustomerList {
    return CustomerListFromJSONTyped(json, false);
}

export function CustomerListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CustomerGetDataFromJSON)),
        'pagination': ProductListPaginationFromJSON(json['pagination']),
    };
}

export function CustomerListToJSON(json: any): CustomerList {
    return CustomerListToJSONTyped(json, false);
}

export function CustomerListToJSONTyped(value?: CustomerList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(CustomerGetDataToJSON)),
        'pagination': ProductListPaginationToJSON(value['pagination']),
    };
}

