/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerCreate
 */
export interface CustomerCreate {
    /**
     * 
     * @type {string}
     * @memberof CustomerCreate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreate
     */
    externalUserId: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerCreate
     */
    phone?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CustomerCreate
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the CustomerCreate interface.
 */
export function instanceOfCustomerCreate(value: object): value is CustomerCreate {
    if (!('externalUserId' in value) || value['externalUserId'] === undefined) return false;
    return true;
}

export function CustomerCreateFromJSON(json: any): CustomerCreate {
    return CustomerCreateFromJSONTyped(json, false);
}

export function CustomerCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'externalUserId': json['externalUserId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function CustomerCreateToJSON(json: any): CustomerCreate {
    return CustomerCreateToJSONTyped(json, false);
}

export function CustomerCreateToJSONTyped(value?: CustomerCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'externalUserId': value['externalUserId'],
        'phone': value['phone'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

