/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteConnectRevokeRequest
 */
export interface DeleteConnectRevokeRequest {
    /**
     * 
     * @type {string}
     * @memberof DeleteConnectRevokeRequest
     */
    platformId: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteConnectRevokeRequest
     */
    platformSecret: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteConnectRevokeRequest
     */
    connectionId: string;
}

/**
 * Check if a given object implements the DeleteConnectRevokeRequest interface.
 */
export function instanceOfDeleteConnectRevokeRequest(value: object): value is DeleteConnectRevokeRequest {
    if (!('platformId' in value) || value['platformId'] === undefined) return false;
    if (!('platformSecret' in value) || value['platformSecret'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    return true;
}

export function DeleteConnectRevokeRequestFromJSON(json: any): DeleteConnectRevokeRequest {
    return DeleteConnectRevokeRequestFromJSONTyped(json, false);
}

export function DeleteConnectRevokeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteConnectRevokeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'platformId': json['platform_id'],
        'platformSecret': json['platform_secret'],
        'connectionId': json['connection_id'],
    };
}

export function DeleteConnectRevokeRequestToJSON(json: any): DeleteConnectRevokeRequest {
    return DeleteConnectRevokeRequestToJSONTyped(json, false);
}

export function DeleteConnectRevokeRequestToJSONTyped(value?: DeleteConnectRevokeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform_id': value['platformId'],
        'platform_secret': value['platformSecret'],
        'connection_id': value['connectionId'],
    };
}

