/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCheckoutSessionPublicByIdPaymentStatus200Response
 */
export interface GetCheckoutSessionPublicByIdPaymentStatus200Response {
    /**
     * 
     */
    status: GetCheckoutSessionPublicByIdPaymentStatus200ResponseStatusEnum;
    /**
     * 
     */
    claimExpiresAt: string | null;
    /**
     * 
     */
    successUrl: string | null;
}


/**
 * @export
 */
export const GetCheckoutSessionPublicByIdPaymentStatus200ResponseStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Expired: 'expired',
    Cancelled: 'cancelled',
    Failed: 'failed',
} as const;
export type GetCheckoutSessionPublicByIdPaymentStatus200ResponseStatusEnum = typeof GetCheckoutSessionPublicByIdPaymentStatus200ResponseStatusEnum[keyof typeof GetCheckoutSessionPublicByIdPaymentStatus200ResponseStatusEnum];


/**
 * Check if a given object implements the GetCheckoutSessionPublicByIdPaymentStatus200Response interface.
 */
export function instanceOfGetCheckoutSessionPublicByIdPaymentStatus200Response(value: object): value is GetCheckoutSessionPublicByIdPaymentStatus200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('claimExpiresAt' in value) || value['claimExpiresAt'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    return true;
}

export function GetCheckoutSessionPublicByIdPaymentStatus200ResponseFromJSON(json: any): GetCheckoutSessionPublicByIdPaymentStatus200Response {
    return GetCheckoutSessionPublicByIdPaymentStatus200ResponseFromJSONTyped(json, false);
}

export function GetCheckoutSessionPublicByIdPaymentStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCheckoutSessionPublicByIdPaymentStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'claimExpiresAt': json['claimExpiresAt'],
        'successUrl': json['successUrl'],
    };
}

export function GetCheckoutSessionPublicByIdPaymentStatus200ResponseToJSON(json: any): GetCheckoutSessionPublicByIdPaymentStatus200Response {
    return GetCheckoutSessionPublicByIdPaymentStatus200ResponseToJSONTyped(json, false);
}

export function GetCheckoutSessionPublicByIdPaymentStatus200ResponseToJSONTyped(value?: GetCheckoutSessionPublicByIdPaymentStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'claimExpiresAt': value['claimExpiresAt'],
        'successUrl': value['successUrl'],
    };
}

