/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetOrganizationById200ResponseData } from './GetOrganizationById200ResponseData';
import {
    GetOrganizationById200ResponseDataFromJSON,
    GetOrganizationById200ResponseDataFromJSONTyped,
    GetOrganizationById200ResponseDataToJSON,
    GetOrganizationById200ResponseDataToJSONTyped,
} from './GetOrganizationById200ResponseData';

/**
 * 
 * @export
 * @interface GetOrganizationById200Response
 */
export interface GetOrganizationById200Response {
    /**
     * 
     * @type {GetOrganizationById200ResponseData}
     * @memberof GetOrganizationById200Response
     */
    data: GetOrganizationById200ResponseData;
}

/**
 * Check if a given object implements the GetOrganizationById200Response interface.
 */
export function instanceOfGetOrganizationById200Response(value: object): value is GetOrganizationById200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function GetOrganizationById200ResponseFromJSON(json: any): GetOrganizationById200Response {
    return GetOrganizationById200ResponseFromJSONTyped(json, false);
}

export function GetOrganizationById200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganizationById200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': GetOrganizationById200ResponseDataFromJSON(json['data']),
    };
}

export function GetOrganizationById200ResponseToJSON(json: any): GetOrganizationById200Response {
    return GetOrganizationById200ResponseToJSONTyped(json, false);
}

export function GetOrganizationById200ResponseToJSONTyped(value?: GetOrganizationById200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': GetOrganizationById200ResponseDataToJSON(value['data']),
    };
}

