/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetOrganizationById200ResponseData
 */
export interface GetOrganizationById200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof GetOrganizationById200ResponseData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrganizationById200ResponseData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrganizationById200ResponseData
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof GetOrganizationById200ResponseData
     */
    website: string | null;
}

/**
 * Check if a given object implements the GetOrganizationById200ResponseData interface.
 */
export function instanceOfGetOrganizationById200ResponseData(value: object): value is GetOrganizationById200ResponseData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    return true;
}

export function GetOrganizationById200ResponseDataFromJSON(json: any): GetOrganizationById200ResponseData {
    return GetOrganizationById200ResponseDataFromJSONTyped(json, false);
}

export function GetOrganizationById200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetOrganizationById200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'phoneNumber': json['phoneNumber'],
        'website': json['website'],
    };
}

export function GetOrganizationById200ResponseDataToJSON(json: any): GetOrganizationById200ResponseData {
    return GetOrganizationById200ResponseDataToJSONTyped(json, false);
}

export function GetOrganizationById200ResponseDataToJSONTyped(value?: GetOrganizationById200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'phoneNumber': value['phoneNumber'],
        'website': value['website'],
    };
}

