/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetPaymentByIdStatus200Response
 */
export interface GetPaymentByIdStatus200Response {
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    status: GetPaymentByIdStatus200ResponseStatusEnum;
    /**
     * 
     */
    referenceId: string | null;
    /**
     * 
     */
    claimExpiresAt: string | null;
}


/**
 * @export
 */
export const GetPaymentByIdStatus200ResponseStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Expired: 'expired',
    Cancelled: 'cancelled',
    Failed: 'failed',
} as const;
export type GetPaymentByIdStatus200ResponseStatusEnum = typeof GetPaymentByIdStatus200ResponseStatusEnum[keyof typeof GetPaymentByIdStatus200ResponseStatusEnum];


/**
 * Check if a given object implements the GetPaymentByIdStatus200Response interface.
 */
export function instanceOfGetPaymentByIdStatus200Response(value: object): value is GetPaymentByIdStatus200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('referenceId' in value) || value['referenceId'] === undefined) return false;
    if (!('claimExpiresAt' in value) || value['claimExpiresAt'] === undefined) return false;
    return true;
}

export function GetPaymentByIdStatus200ResponseFromJSON(json: any): GetPaymentByIdStatus200Response {
    return GetPaymentByIdStatus200ResponseFromJSONTyped(json, false);
}

export function GetPaymentByIdStatus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaymentByIdStatus200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'referenceId': json['referenceId'],
        'claimExpiresAt': json['claimExpiresAt'],
    };
}

export function GetPaymentByIdStatus200ResponseToJSON(json: any): GetPaymentByIdStatus200Response {
    return GetPaymentByIdStatus200ResponseToJSONTyped(json, false);
}

export function GetPaymentByIdStatus200ResponseToJSONTyped(value?: GetPaymentByIdStatus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'referenceId': value['referenceId'],
        'claimExpiresAt': value['claimExpiresAt'],
    };
}

