/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetProductsPageParameter
 */
export interface GetProductsPageParameter {
}

/**
 * Check if a given object implements the GetProductsPageParameter interface.
 */
export function instanceOfGetProductsPageParameter(value: object): value is GetProductsPageParameter {
    return true;
}

export function GetProductsPageParameterFromJSON(json: any): GetProductsPageParameter {
    return GetProductsPageParameterFromJSONTyped(json, false);
}

export function GetProductsPageParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetProductsPageParameter {
    return json;
}

export function GetProductsPageParameterToJSON(json: any): GetProductsPageParameter {
    return GetProductsPageParameterToJSONTyped(json, false);
}

export function GetProductsPageParameterToJSONTyped(value?: GetProductsPageParameter | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

