/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceGetData } from './InvoiceGetData';
import {
    InvoiceGetDataFromJSON,
    InvoiceGetDataFromJSONTyped,
    InvoiceGetDataToJSON,
    InvoiceGetDataToJSONTyped,
} from './InvoiceGetData';

/**
 * 
 * @export
 * @interface InvoiceGet
 */
export interface InvoiceGet {
    /**
     * 
     * @type {InvoiceGetData}
     * @memberof InvoiceGet
     */
    data: InvoiceGetData;
}

/**
 * Check if a given object implements the InvoiceGet interface.
 */
export function instanceOfInvoiceGet(value: object): value is InvoiceGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function InvoiceGetFromJSON(json: any): InvoiceGet {
    return InvoiceGetFromJSONTyped(json, false);
}

export function InvoiceGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': InvoiceGetDataFromJSON(json['data']),
    };
}

export function InvoiceGetToJSON(json: any): InvoiceGet {
    return InvoiceGetToJSONTyped(json, false);
}

export function InvoiceGetToJSONTyped(value?: InvoiceGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': InvoiceGetDataToJSON(value['data']),
    };
}

