/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductListPagination } from './ProductListPagination';
import {
    ProductListPaginationFromJSON,
    ProductListPaginationFromJSONTyped,
    ProductListPaginationToJSON,
    ProductListPaginationToJSONTyped,
} from './ProductListPagination';
import type { InvoiceGetData } from './InvoiceGetData';
import {
    InvoiceGetDataFromJSON,
    InvoiceGetDataFromJSONTyped,
    InvoiceGetDataToJSON,
    InvoiceGetDataToJSONTyped,
} from './InvoiceGetData';

/**
 * 
 * @export
 * @interface InvoiceList
 */
export interface InvoiceList {
    /**
     * 
     * @type {Array<InvoiceGetData>}
     * @memberof InvoiceList
     */
    data: Array<InvoiceGetData>;
    /**
     * 
     * @type {ProductListPagination}
     * @memberof InvoiceList
     */
    pagination: ProductListPagination;
}

/**
 * Check if a given object implements the InvoiceList interface.
 */
export function instanceOfInvoiceList(value: object): value is InvoiceList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function InvoiceListFromJSON(json: any): InvoiceList {
    return InvoiceListFromJSONTyped(json, false);
}

export function InvoiceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(InvoiceGetDataFromJSON)),
        'pagination': ProductListPaginationFromJSON(json['pagination']),
    };
}

export function InvoiceListToJSON(json: any): InvoiceList {
    return InvoiceListToJSONTyped(json, false);
}

export function InvoiceListToJSONTyped(value?: InvoiceList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(InvoiceGetDataToJSON)),
        'pagination': ProductListPaginationToJSON(value['pagination']),
    };
}

