/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceGetData
 */
export interface InvoiceGetData {
    /**
     * 
     * @type {string}
     * @memberof InvoiceGetData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceGetData
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceGetData
     */
    organizationId: string;
    /**
     * 
     * @type {InvoiceGetDataStatusEnum}
     * @memberof InvoiceGetData
     */
    status: InvoiceGetDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof InvoiceGetData
     */
    amount: string;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceGetData
     */
    dueDate: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceGetData
     */
    paymentRequestId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceGetData
     */
    createdAt: Date | null;
}


/**
 * @export
 */
export const InvoiceGetDataStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Void: 'void',
    Refunded: 'refunded'
} as const;
export type InvoiceGetDataStatusEnum = typeof InvoiceGetDataStatusEnum[keyof typeof InvoiceGetDataStatusEnum];


/**
 * Check if a given object implements the InvoiceGetData interface.
 */
export function instanceOfInvoiceGetData(value: object): value is InvoiceGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('dueDate' in value) || value['dueDate'] === undefined) return false;
    if (!('paymentRequestId' in value) || value['paymentRequestId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function InvoiceGetDataFromJSON(json: any): InvoiceGetData {
    return InvoiceGetDataFromJSONTyped(json, false);
}

export function InvoiceGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'customerId': json['customerId'],
        'organizationId': json['organizationId'],
        'status': json['status'],
        'amount': json['amount'],
        'dueDate': (json['dueDate'] == null ? null : new Date(json['dueDate'])),
        'paymentRequestId': json['paymentRequestId'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
    };
}

export function InvoiceGetDataToJSON(json: any): InvoiceGetData {
    return InvoiceGetDataToJSONTyped(json, false);
}

export function InvoiceGetDataToJSONTyped(value?: InvoiceGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'organizationId': value['organizationId'],
        'status': value['status'],
        'amount': value['amount'],
        'dueDate': value['dueDate'] == null ? value['dueDate'] : value['dueDate'].toISOString(),
        'paymentRequestId': value['paymentRequestId'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

