/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetProductsPageParameter } from './GetProductsPageParameter';
import {
    GetProductsPageParameterFromJSON,
    GetProductsPageParameterFromJSONTyped,
    GetProductsPageParameterToJSON,
    GetProductsPageParameterToJSONTyped,
} from './GetProductsPageParameter';

/**
 * 
 * @export
 * @interface PaymentRequestCreate
 */
export interface PaymentRequestCreate {
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestCreate
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestCreate
     */
    transactionId: string;
    /**
     * 
     * @type {GetProductsPageParameter}
     * @memberof PaymentRequestCreate
     */
    amount: GetProductsPageParameter;
}

/**
 * Check if a given object implements the PaymentRequestCreate interface.
 */
export function instanceOfPaymentRequestCreate(value: object): value is PaymentRequestCreate {
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function PaymentRequestCreateFromJSON(json: any): PaymentRequestCreate {
    return PaymentRequestCreateFromJSONTyped(json, false);
}

export function PaymentRequestCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'transactionId': json['transactionId'],
        'amount': GetProductsPageParameterFromJSON(json['amount']),
    };
}

export function PaymentRequestCreateToJSON(json: any): PaymentRequestCreate {
    return PaymentRequestCreateToJSONTyped(json, false);
}

export function PaymentRequestCreateToJSONTyped(value?: PaymentRequestCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phoneNumber': value['phoneNumber'],
        'transactionId': value['transactionId'],
        'amount': GetProductsPageParameterToJSON(value['amount']),
    };
}

