/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestRefreshStatusBankingApiResponsesInner
 */
export interface PaymentRequestRefreshStatusBankingApiResponsesInner {
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestRefreshStatusBankingApiResponsesInner
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestRefreshStatusBankingApiResponsesInner
     */
    configurationId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestRefreshStatusBankingApiResponsesInner
     */
    configurationType: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestRefreshStatusBankingApiResponsesInner
     */
    outcome: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestRefreshStatusBankingApiResponsesInner
     */
    body: string;
}

/**
 * Check if a given object implements the PaymentRequestRefreshStatusBankingApiResponsesInner interface.
 */
export function instanceOfPaymentRequestRefreshStatusBankingApiResponsesInner(value: object): value is PaymentRequestRefreshStatusBankingApiResponsesInner {
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    if (!('configurationType' in value) || value['configurationType'] === undefined) return false;
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function PaymentRequestRefreshStatusBankingApiResponsesInnerFromJSON(json: any): PaymentRequestRefreshStatusBankingApiResponsesInner {
    return PaymentRequestRefreshStatusBankingApiResponsesInnerFromJSONTyped(json, false);
}

export function PaymentRequestRefreshStatusBankingApiResponsesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestRefreshStatusBankingApiResponsesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'],
        'configurationId': json['configurationId'],
        'configurationType': json['configurationType'],
        'outcome': json['outcome'],
        'body': json['body'],
    };
}

export function PaymentRequestRefreshStatusBankingApiResponsesInnerToJSON(json: any): PaymentRequestRefreshStatusBankingApiResponsesInner {
    return PaymentRequestRefreshStatusBankingApiResponsesInnerToJSONTyped(json, false);
}

export function PaymentRequestRefreshStatusBankingApiResponsesInnerToJSONTyped(value?: PaymentRequestRefreshStatusBankingApiResponsesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionId': value['transactionId'],
        'configurationId': value['configurationId'],
        'configurationType': value['configurationType'],
        'outcome': value['outcome'],
        'body': value['body'],
    };
}

