/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentRequestGetData } from './PaymentRequestGetData';
import {
    PaymentRequestGetDataFromJSON,
    PaymentRequestGetDataFromJSONTyped,
    PaymentRequestGetDataToJSON,
    PaymentRequestGetDataToJSONTyped,
} from './PaymentRequestGetData';
import type { PaymentRequestRefreshStatusBankingApiResponsesInner } from './PaymentRequestRefreshStatusBankingApiResponsesInner';
import {
    PaymentRequestRefreshStatusBankingApiResponsesInnerFromJSON,
    PaymentRequestRefreshStatusBankingApiResponsesInnerFromJSONTyped,
    PaymentRequestRefreshStatusBankingApiResponsesInnerToJSON,
    PaymentRequestRefreshStatusBankingApiResponsesInnerToJSONTyped,
} from './PaymentRequestRefreshStatusBankingApiResponsesInner';

/**
 * 
 * @export
 * @interface PaymentRequestRefreshStatus
 */
export interface PaymentRequestRefreshStatus {
    /**
     * 
     * @type {PaymentRequestGetData}
     * @memberof PaymentRequestRefreshStatus
     */
    data: PaymentRequestGetData;
    /**
     * 
     * @type {Array<PaymentRequestRefreshStatusBankingApiResponsesInner>}
     * @memberof PaymentRequestRefreshStatus
     */
    bankingApiResponses: Array<PaymentRequestRefreshStatusBankingApiResponsesInner>;
}

/**
 * Check if a given object implements the PaymentRequestRefreshStatus interface.
 */
export function instanceOfPaymentRequestRefreshStatus(value: object): value is PaymentRequestRefreshStatus {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('bankingApiResponses' in value) || value['bankingApiResponses'] === undefined) return false;
    return true;
}

export function PaymentRequestRefreshStatusFromJSON(json: any): PaymentRequestRefreshStatus {
    return PaymentRequestRefreshStatusFromJSONTyped(json, false);
}

export function PaymentRequestRefreshStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestRefreshStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaymentRequestGetDataFromJSON(json['data']),
        'bankingApiResponses': ((json['bankingApiResponses'] as Array<any>).map(PaymentRequestRefreshStatusBankingApiResponsesInnerFromJSON)),
    };
}

export function PaymentRequestRefreshStatusToJSON(json: any): PaymentRequestRefreshStatus {
    return PaymentRequestRefreshStatusToJSONTyped(json, false);
}

export function PaymentRequestRefreshStatusToJSONTyped(value?: PaymentRequestRefreshStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaymentRequestGetDataToJSON(value['data']),
        'bankingApiResponses': ((value['bankingApiResponses'] as Array<any>).map(PaymentRequestRefreshStatusBankingApiResponsesInnerToJSON)),
    };
}

