/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentUpdate
 */
export interface PaymentUpdate {
    /**
     * 
     * @type {PaymentUpdateStatusEnum}
     * @memberof PaymentUpdate
     */
    status?: PaymentUpdateStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PaymentUpdate
     */
    amount?: number;
}


/**
 * @export
 */
export const PaymentUpdateStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type PaymentUpdateStatusEnum = typeof PaymentUpdateStatusEnum[keyof typeof PaymentUpdateStatusEnum];


/**
 * Check if a given object implements the PaymentUpdate interface.
 */
export function instanceOfPaymentUpdate(value: object): value is PaymentUpdate {
    return true;
}

export function PaymentUpdateFromJSON(json: any): PaymentUpdate {
    return PaymentUpdateFromJSONTyped(json, false);
}

export function PaymentUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'amount': json['amount'] == null ? undefined : json['amount'],
    };
}

export function PaymentUpdateToJSON(json: any): PaymentUpdate {
    return PaymentUpdateToJSONTyped(json, false);
}

export function PaymentUpdateToJSONTyped(value?: PaymentUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'amount': value['amount'],
    };
}

