/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentCreate
 */
export interface PaymentCreate {
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    configurationId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentCreate
     */
    passCode: string;
}

/**
 * Check if a given object implements the PaymentCreate interface.
 */
export function instanceOfPaymentCreate(value: object): value is PaymentCreate {
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('passCode' in value) || value['passCode'] === undefined) return false;
    return true;
}

export function PaymentCreateFromJSON(json: any): PaymentCreate {
    return PaymentCreateFromJSONTyped(json, false);
}

export function PaymentCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'configurationId': json['configurationId'],
        'transactionId': json['transactionId'],
        'phoneNumber': json['phoneNumber'],
        'passCode': json['passCode'],
    };
}

export function PaymentCreateToJSON(json: any): PaymentCreate {
    return PaymentCreateToJSONTyped(json, false);
}

export function PaymentCreateToJSONTyped(value?: PaymentCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'configurationId': value['configurationId'],
        'transactionId': value['transactionId'],
        'phoneNumber': value['phoneNumber'],
        'passCode': value['passCode'],
    };
}

