/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentRequestGetData } from './PaymentRequestGetData';
import {
    PaymentRequestGetDataFromJSON,
    PaymentRequestGetDataFromJSONTyped,
    PaymentRequestGetDataToJSON,
    PaymentRequestGetDataToJSONTyped,
} from './PaymentRequestGetData';

/**
 * 
 * @export
 * @interface PaymentRequestGet
 */
export interface PaymentRequestGet {
    /**
     * 
     * @type {PaymentRequestGetData}
     * @memberof PaymentRequestGet
     */
    data: PaymentRequestGetData;
}

/**
 * Check if a given object implements the PaymentRequestGet interface.
 */
export function instanceOfPaymentRequestGet(value: object): value is PaymentRequestGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaymentRequestGetFromJSON(json: any): PaymentRequestGet {
    return PaymentRequestGetFromJSONTyped(json, false);
}

export function PaymentRequestGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaymentRequestGetDataFromJSON(json['data']),
    };
}

export function PaymentRequestGetToJSON(json: any): PaymentRequestGet {
    return PaymentRequestGetToJSONTyped(json, false);
}

export function PaymentRequestGetToJSONTyped(value?: PaymentRequestGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaymentRequestGetDataToJSON(value['data']),
    };
}

