/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentGetData } from './PaymentGetData';
import {
    PaymentGetDataFromJSON,
    PaymentGetDataFromJSONTyped,
    PaymentGetDataToJSON,
    PaymentGetDataToJSONTyped,
} from './PaymentGetData';

/**
 * 
 * @export
 * @interface PaymentGet
 */
export interface PaymentGet {
    /**
     * 
     * @type {PaymentGetData}
     * @memberof PaymentGet
     */
    data: PaymentGetData;
}

/**
 * Check if a given object implements the PaymentGet interface.
 */
export function instanceOfPaymentGet(value: object): value is PaymentGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaymentGetFromJSON(json: any): PaymentGet {
    return PaymentGetFromJSONTyped(json, false);
}

export function PaymentGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaymentGetDataFromJSON(json['data']),
    };
}

export function PaymentGetToJSON(json: any): PaymentGet {
    return PaymentGetToJSONTyped(json, false);
}

export function PaymentGetToJSONTyped(value?: PaymentGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PaymentGetDataToJSON(value['data']),
    };
}

