/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestGetData
 */
export interface PaymentRequestGetData {
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestGetData
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestGetData
     */
    amount: number;
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestGetData
     */
    totalAmount: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestGetData
     */
    phoneNumber: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestGetData
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestGetData
     */
    environmentId: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestGetData
     */
    retryCount: number;
    /**
     * 
     * @type {Date}
     * @memberof PaymentRequestGetData
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaymentRequestGetData
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the PaymentRequestGetData interface.
 */
export function instanceOfPaymentRequestGetData(value: object): value is PaymentRequestGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('totalAmount' in value) || value['totalAmount'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('environmentId' in value) || value['environmentId'] === undefined) return false;
    if (!('retryCount' in value) || value['retryCount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PaymentRequestGetDataFromJSON(json: any): PaymentRequestGetData {
    return PaymentRequestGetDataFromJSONTyped(json, false);
}

export function PaymentRequestGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'totalAmount': json['totalAmount'],
        'phoneNumber': json['phoneNumber'],
        'transactionId': json['transactionId'],
        'environmentId': json['environmentId'],
        'retryCount': json['retryCount'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PaymentRequestGetDataToJSON(json: any): PaymentRequestGetData {
    return PaymentRequestGetDataToJSONTyped(json, false);
}

export function PaymentRequestGetDataToJSONTyped(value?: PaymentRequestGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'totalAmount': value['totalAmount'],
        'phoneNumber': value['phoneNumber'],
        'transactionId': value['transactionId'],
        'environmentId': value['environmentId'],
        'retryCount': value['retryCount'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

