/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentGetData
 */
export interface PaymentGetData {
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentGetData
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    phoneNumber: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    passCode: string | null;
    /**
     * 
     * @type {PaymentGetDataStatusEnum}
     * @memberof PaymentGetData
     */
    status: PaymentGetDataStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    environmentId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    paymentRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    configurationId: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    referenceId: string | null;
    /**
     * 
     * @type {any}
     * @memberof PaymentGetData
     */
    metadata: any | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentGetData
     */
    payoutId: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PaymentGetData
     */
    completedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PaymentGetData
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PaymentGetData
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const PaymentGetDataStatusEnum = {
    Pending: 'pending',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type PaymentGetDataStatusEnum = typeof PaymentGetDataStatusEnum[keyof typeof PaymentGetDataStatusEnum];


/**
 * Check if a given object implements the PaymentGetData interface.
 */
export function instanceOfPaymentGetData(value: object): value is PaymentGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('passCode' in value) || value['passCode'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('environmentId' in value) || value['environmentId'] === undefined) return false;
    if (!('paymentRequestId' in value) || value['paymentRequestId'] === undefined) return false;
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    if (!('referenceId' in value) || value['referenceId'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('payoutId' in value) || value['payoutId'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PaymentGetDataFromJSON(json: any): PaymentGetData {
    return PaymentGetDataFromJSONTyped(json, false);
}

export function PaymentGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'amount': json['amount'],
        'phoneNumber': json['phoneNumber'],
        'passCode': json['passCode'],
        'status': json['status'],
        'environmentId': json['environmentId'],
        'paymentRequestId': json['paymentRequestId'],
        'configurationId': json['configurationId'],
        'referenceId': json['referenceId'],
        'metadata': json['metadata'],
        'payoutId': json['payoutId'],
        'completedAt': (json['completedAt'] == null ? null : new Date(json['completedAt'])),
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PaymentGetDataToJSON(json: any): PaymentGetData {
    return PaymentGetDataToJSONTyped(json, false);
}

export function PaymentGetDataToJSONTyped(value?: PaymentGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'amount': value['amount'],
        'phoneNumber': value['phoneNumber'],
        'passCode': value['passCode'],
        'status': value['status'],
        'environmentId': value['environmentId'],
        'paymentRequestId': value['paymentRequestId'],
        'configurationId': value['configurationId'],
        'referenceId': value['referenceId'],
        'metadata': value['metadata'],
        'payoutId': value['payoutId'],
        'completedAt': value['completedAt'] == null ? value['completedAt'] : value['completedAt'].toISOString(),
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

