/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostMasriviInitiate200Response
 */
export interface PostMasriviInitiate200Response {
    /**
     * 
     * @type {any}
     * @memberof PostMasriviInitiate200Response
     */
    formData: any | null;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiate200Response
     */
    purchaseref: string;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiate200Response
     */
    paymentId: string;
}

/**
 * Check if a given object implements the PostMasriviInitiate200Response interface.
 */
export function instanceOfPostMasriviInitiate200Response(value: object): value is PostMasriviInitiate200Response {
    if (!('formData' in value) || value['formData'] === undefined) return false;
    if (!('purchaseref' in value) || value['purchaseref'] === undefined) return false;
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    return true;
}

export function PostMasriviInitiate200ResponseFromJSON(json: any): PostMasriviInitiate200Response {
    return PostMasriviInitiate200ResponseFromJSONTyped(json, false);
}

export function PostMasriviInitiate200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMasriviInitiate200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'formData': json['formData'],
        'purchaseref': json['purchaseref'],
        'paymentId': json['paymentId'],
    };
}

export function PostMasriviInitiate200ResponseToJSON(json: any): PostMasriviInitiate200Response {
    return PostMasriviInitiate200ResponseToJSONTyped(json, false);
}

export function PostMasriviInitiate200ResponseToJSONTyped(value?: PostMasriviInitiate200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'formData': value['formData'],
        'purchaseref': value['purchaseref'],
        'paymentId': value['paymentId'],
    };
}

