/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPayment200Response
 */
export interface PostPayment200Response {
    /**
     * 
     * @type {string}
     * @memberof PostPayment200Response
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PostPayment200Response
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PostPayment200Response
     */
    referenceId: string | null;
    /**
     * 
     * @type {any}
     * @memberof PostPayment200Response
     */
    metadata?: any | null;
}

/**
 * Check if a given object implements the PostPayment200Response interface.
 */
export function instanceOfPostPayment200Response(value: object): value is PostPayment200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('referenceId' in value) || value['referenceId'] === undefined) return false;
    return true;
}

export function PostPayment200ResponseFromJSON(json: any): PostPayment200Response {
    return PostPayment200ResponseFromJSONTyped(json, false);
}

export function PostPayment200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPayment200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'referenceId': json['referenceId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function PostPayment200ResponseToJSON(json: any): PostPayment200Response {
    return PostPayment200ResponseToJSONTyped(json, false);
}

export function PostPayment200ResponseToJSONTyped(value?: PostPayment200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'referenceId': value['referenceId'],
        'metadata': value['metadata'],
    };
}

