/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostMasriviInitiateRequest
 */
export interface PostMasriviInitiateRequest {
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiateRequest
     */
    transactionId: string;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiateRequest
     */
    configurationId: string;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiateRequest
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiateRequest
     */
    acceptUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiateRequest
     */
    declineUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PostMasriviInitiateRequest
     */
    cancelUrl?: string;
}

/**
 * Check if a given object implements the PostMasriviInitiateRequest interface.
 */
export function instanceOfPostMasriviInitiateRequest(value: object): value is PostMasriviInitiateRequest {
    if (!('transactionId' in value) || value['transactionId'] === undefined) return false;
    if (!('configurationId' in value) || value['configurationId'] === undefined) return false;
    return true;
}

export function PostMasriviInitiateRequestFromJSON(json: any): PostMasriviInitiateRequest {
    return PostMasriviInitiateRequestFromJSONTyped(json, false);
}

export function PostMasriviInitiateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMasriviInitiateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'],
        'configurationId': json['configurationId'],
        'phoneNumber': json['phoneNumber'] == null ? undefined : json['phoneNumber'],
        'acceptUrl': json['acceptUrl'] == null ? undefined : json['acceptUrl'],
        'declineUrl': json['declineUrl'] == null ? undefined : json['declineUrl'],
        'cancelUrl': json['cancelUrl'] == null ? undefined : json['cancelUrl'],
    };
}

export function PostMasriviInitiateRequestToJSON(json: any): PostMasriviInitiateRequest {
    return PostMasriviInitiateRequestToJSONTyped(json, false);
}

export function PostMasriviInitiateRequestToJSONTyped(value?: PostMasriviInitiateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transactionId': value['transactionId'],
        'configurationId': value['configurationId'],
        'phoneNumber': value['phoneNumber'],
        'acceptUrl': value['acceptUrl'],
        'declineUrl': value['declineUrl'],
        'cancelUrl': value['cancelUrl'],
    };
}

