/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostConnectExchange200ResponseData
 */
export interface PostConnectExchange200ResponseData {
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchange200ResponseData
     */
    publishableKey: string;
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchange200ResponseData
     */
    secretKey: string;
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchange200ResponseData
     */
    webhookSecret: string;
}

/**
 * Check if a given object implements the PostConnectExchange200ResponseData interface.
 */
export function instanceOfPostConnectExchange200ResponseData(value: object): value is PostConnectExchange200ResponseData {
    if (!('publishableKey' in value) || value['publishableKey'] === undefined) return false;
    if (!('secretKey' in value) || value['secretKey'] === undefined) return false;
    if (!('webhookSecret' in value) || value['webhookSecret'] === undefined) return false;
    return true;
}

export function PostConnectExchange200ResponseDataFromJSON(json: any): PostConnectExchange200ResponseData {
    return PostConnectExchange200ResponseDataFromJSONTyped(json, false);
}

export function PostConnectExchange200ResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostConnectExchange200ResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'publishableKey': json['publishableKey'],
        'secretKey': json['secretKey'],
        'webhookSecret': json['webhookSecret'],
    };
}

export function PostConnectExchange200ResponseDataToJSON(json: any): PostConnectExchange200ResponseData {
    return PostConnectExchange200ResponseDataToJSONTyped(json, false);
}

export function PostConnectExchange200ResponseDataToJSONTyped(value?: PostConnectExchange200ResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'publishableKey': value['publishableKey'],
        'secretKey': value['secretKey'],
        'webhookSecret': value['webhookSecret'],
    };
}

