/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCheckoutSessionPublicByIdSimulateTransferRequest
 */
export interface PostCheckoutSessionPublicByIdSimulateTransferRequest {
    /**
     * 
     */
    paymentId: string;
}

/**
 * Check if a given object implements the PostCheckoutSessionPublicByIdSimulateTransferRequest interface.
 */
export function instanceOfPostCheckoutSessionPublicByIdSimulateTransferRequest(value: object): value is PostCheckoutSessionPublicByIdSimulateTransferRequest {
    if (!('paymentId' in value) || value['paymentId'] === undefined) return false;
    return true;
}

export function PostCheckoutSessionPublicByIdSimulateTransferRequestFromJSON(json: any): PostCheckoutSessionPublicByIdSimulateTransferRequest {
    return PostCheckoutSessionPublicByIdSimulateTransferRequestFromJSONTyped(json, false);
}

export function PostCheckoutSessionPublicByIdSimulateTransferRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCheckoutSessionPublicByIdSimulateTransferRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentId': json['paymentId'],
    };
}

export function PostCheckoutSessionPublicByIdSimulateTransferRequestToJSON(json: any): PostCheckoutSessionPublicByIdSimulateTransferRequest {
    return PostCheckoutSessionPublicByIdSimulateTransferRequestToJSONTyped(json, false);
}

export function PostCheckoutSessionPublicByIdSimulateTransferRequestToJSONTyped(value?: PostCheckoutSessionPublicByIdSimulateTransferRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentId': value['paymentId'],
    };
}

