/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPaymentByIdSimulateTransfer200Response
 */
export interface PostPaymentByIdSimulateTransfer200Response {
    /**
     * 
     */
    outcome: PostPaymentByIdSimulateTransfer200ResponseOutcomeEnum;
}


/**
 * @export
 */
export const PostPaymentByIdSimulateTransfer200ResponseOutcomeEnum = {
    Matched: 'matched',
    Unmatched: 'unmatched',
    Skipped: 'skipped',
} as const;
export type PostPaymentByIdSimulateTransfer200ResponseOutcomeEnum = typeof PostPaymentByIdSimulateTransfer200ResponseOutcomeEnum[keyof typeof PostPaymentByIdSimulateTransfer200ResponseOutcomeEnum];


/**
 * Check if a given object implements the PostPaymentByIdSimulateTransfer200Response interface.
 */
export function instanceOfPostPaymentByIdSimulateTransfer200Response(value: object): value is PostPaymentByIdSimulateTransfer200Response {
    if (!('outcome' in value) || value['outcome'] === undefined) return false;
    return true;
}

export function PostPaymentByIdSimulateTransfer200ResponseFromJSON(json: any): PostPaymentByIdSimulateTransfer200Response {
    return PostPaymentByIdSimulateTransfer200ResponseFromJSONTyped(json, false);
}

export function PostPaymentByIdSimulateTransfer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPaymentByIdSimulateTransfer200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'outcome': json['outcome'],
    };
}

export function PostPaymentByIdSimulateTransfer200ResponseToJSON(json: any): PostPaymentByIdSimulateTransfer200Response {
    return PostPaymentByIdSimulateTransfer200ResponseToJSONTyped(json, false);
}

export function PostPaymentByIdSimulateTransfer200ResponseToJSONTyped(value?: PostPaymentByIdSimulateTransfer200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'outcome': value['outcome'],
    };
}

