/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostCheckoutSessionPublicByIdPay200Response
 */
export interface PostCheckoutSessionPublicByIdPay200Response {
    /**
     * 
     * @type {string}
     * @memberof PostCheckoutSessionPublicByIdPay200Response
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof PostCheckoutSessionPublicByIdPay200Response
     */
    referenceId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostCheckoutSessionPublicByIdPay200Response
     */
    paymentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PostCheckoutSessionPublicByIdPay200Response
     */
    successUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostCheckoutSessionPublicByIdPay200Response
     */
    provider?: string;
    /**
     * 
     * @type {any}
     * @memberof PostCheckoutSessionPublicByIdPay200Response
     */
    formData?: any | null;
}

/**
 * Check if a given object implements the PostCheckoutSessionPublicByIdPay200Response interface.
 */
export function instanceOfPostCheckoutSessionPublicByIdPay200Response(value: object): value is PostCheckoutSessionPublicByIdPay200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PostCheckoutSessionPublicByIdPay200ResponseFromJSON(json: any): PostCheckoutSessionPublicByIdPay200Response {
    return PostCheckoutSessionPublicByIdPay200ResponseFromJSONTyped(json, false);
}

export function PostCheckoutSessionPublicByIdPay200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCheckoutSessionPublicByIdPay200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'referenceId': json['referenceId'] == null ? undefined : json['referenceId'],
        'paymentCode': json['paymentCode'] == null ? undefined : json['paymentCode'],
        'successUrl': json['successUrl'] == null ? undefined : json['successUrl'],
        'provider': json['provider'] == null ? undefined : json['provider'],
        'formData': json['formData'] == null ? undefined : json['formData'],
    };
}

export function PostCheckoutSessionPublicByIdPay200ResponseToJSON(json: any): PostCheckoutSessionPublicByIdPay200Response {
    return PostCheckoutSessionPublicByIdPay200ResponseToJSONTyped(json, false);
}

export function PostCheckoutSessionPublicByIdPay200ResponseToJSONTyped(value?: PostCheckoutSessionPublicByIdPay200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'referenceId': value['referenceId'],
        'paymentCode': value['paymentCode'],
        'successUrl': value['successUrl'],
        'provider': value['provider'],
        'formData': value['formData'],
    };
}

