/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostConnectRevokeRequest
 */
export interface PostConnectRevokeRequest {
    /**
     * 
     */
    platformId: string;
    /**
     * 
     */
    platformSecret: string;
    /**
     * 
     */
    connectionId: string;
}

/**
 * Check if a given object implements the PostConnectRevokeRequest interface.
 */
export function instanceOfPostConnectRevokeRequest(value: object): value is PostConnectRevokeRequest {
    if ((!('platformId' in (value as Record<string, any>)) && !('platform_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['platformId'] === undefined && (value as Record<string, any>)['platform_id'] === undefined)) return false;
    if ((!('platformSecret' in (value as Record<string, any>)) && !('platform_secret' in (value as Record<string, any>))) || ((value as Record<string, any>)['platformSecret'] === undefined && (value as Record<string, any>)['platform_secret'] === undefined)) return false;
    if ((!('connectionId' in (value as Record<string, any>)) && !('connection_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['connectionId'] === undefined && (value as Record<string, any>)['connection_id'] === undefined)) return false;
    return true;
}

export function PostConnectRevokeRequestFromJSON(json: any): PostConnectRevokeRequest {
    return PostConnectRevokeRequestFromJSONTyped(json, false);
}

export function PostConnectRevokeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostConnectRevokeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'platformId': json['platform_id'],
        'platformSecret': json['platform_secret'],
        'connectionId': json['connection_id'],
    };
}

export function PostConnectRevokeRequestToJSON(json: any): PostConnectRevokeRequest {
    return PostConnectRevokeRequestToJSONTyped(json, false);
}

export function PostConnectRevokeRequestToJSONTyped(value?: PostConnectRevokeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform_id': value['platformId'],
        'platform_secret': value['platformSecret'],
        'connection_id': value['connectionId'],
    };
}

