/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostConnectExchangeRequest
 */
export interface PostConnectExchangeRequest {
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchangeRequest
     */
    platformId: string;
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchangeRequest
     */
    platformSecret: string;
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchangeRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchangeRequest
     */
    webhookPaymentCreatedEndpoint: string;
    /**
     * 
     * @type {string}
     * @memberof PostConnectExchangeRequest
     */
    webhookPaymentUpdatedEndpoint: string;
}

/**
 * Check if a given object implements the PostConnectExchangeRequest interface.
 */
export function instanceOfPostConnectExchangeRequest(value: object): value is PostConnectExchangeRequest {
    if (!('platformId' in value) || value['platformId'] === undefined) return false;
    if (!('platformSecret' in value) || value['platformSecret'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('webhookPaymentCreatedEndpoint' in value) || value['webhookPaymentCreatedEndpoint'] === undefined) return false;
    if (!('webhookPaymentUpdatedEndpoint' in value) || value['webhookPaymentUpdatedEndpoint'] === undefined) return false;
    return true;
}

export function PostConnectExchangeRequestFromJSON(json: any): PostConnectExchangeRequest {
    return PostConnectExchangeRequestFromJSONTyped(json, false);
}

export function PostConnectExchangeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostConnectExchangeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'platformId': json['platform_id'],
        'platformSecret': json['platform_secret'],
        'code': json['code'],
        'webhookPaymentCreatedEndpoint': json['webhook_payment_created_endpoint'],
        'webhookPaymentUpdatedEndpoint': json['webhook_payment_updated_endpoint'],
    };
}

export function PostConnectExchangeRequestToJSON(json: any): PostConnectExchangeRequest {
    return PostConnectExchangeRequestToJSONTyped(json, false);
}

export function PostConnectExchangeRequestToJSONTyped(value?: PostConnectExchangeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'platform_id': value['platformId'],
        'platform_secret': value['platformSecret'],
        'code': value['code'],
        'webhook_payment_created_endpoint': value['webhookPaymentCreatedEndpoint'],
        'webhook_payment_updated_endpoint': value['webhookPaymentUpdatedEndpoint'],
    };
}

