/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostConnectRevoke200Response
 */
export interface PostConnectRevoke200Response {
    /**
     * 
     */
    success: boolean;
}

/**
 * Check if a given object implements the PostConnectRevoke200Response interface.
 */
export function instanceOfPostConnectRevoke200Response(value: object): value is PostConnectRevoke200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function PostConnectRevoke200ResponseFromJSON(json: any): PostConnectRevoke200Response {
    return PostConnectRevoke200ResponseFromJSONTyped(json, false);
}

export function PostConnectRevoke200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostConnectRevoke200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function PostConnectRevoke200ResponseToJSON(json: any): PostConnectRevoke200Response {
    return PostConnectRevoke200ResponseToJSONTyped(json, false);
}

export function PostConnectRevoke200ResponseToJSONTyped(value?: PostConnectRevoke200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

