/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostConnectExchange200ResponseData } from './PostConnectExchange200ResponseData';
import {
    PostConnectExchange200ResponseDataFromJSON,
    PostConnectExchange200ResponseDataFromJSONTyped,
    PostConnectExchange200ResponseDataToJSON,
    PostConnectExchange200ResponseDataToJSONTyped,
} from './PostConnectExchange200ResponseData';

/**
 * 
 * @export
 * @interface PostConnectExchange200Response
 */
export interface PostConnectExchange200Response {
    /**
     * 
     * @type {PostConnectExchange200ResponseData}
     * @memberof PostConnectExchange200Response
     */
    data: PostConnectExchange200ResponseData;
}

/**
 * Check if a given object implements the PostConnectExchange200Response interface.
 */
export function instanceOfPostConnectExchange200Response(value: object): value is PostConnectExchange200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PostConnectExchange200ResponseFromJSON(json: any): PostConnectExchange200Response {
    return PostConnectExchange200ResponseFromJSONTyped(json, false);
}

export function PostConnectExchange200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostConnectExchange200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PostConnectExchange200ResponseDataFromJSON(json['data']),
    };
}

export function PostConnectExchange200ResponseToJSON(json: any): PostConnectExchange200Response {
    return PostConnectExchange200ResponseToJSONTyped(json, false);
}

export function PostConnectExchange200ResponseToJSONTyped(value?: PostConnectExchange200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': PostConnectExchange200ResponseDataToJSON(value['data']),
    };
}

