/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceCreate
 */
export interface PriceCreate {
    /**
     * 
     * @type {string}
     * @memberof PriceCreate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PriceCreate
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof PriceCreate
     */
    amount: number;
    /**
     * 
     * @type {PriceCreateIntervalEnum}
     * @memberof PriceCreate
     */
    interval: PriceCreateIntervalEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PriceCreate
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof PriceCreate
     */
    createdAt?: Date | null;
}


/**
 * @export
 */
export const PriceCreateIntervalEnum = {
    Weekly: 'weekly',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type PriceCreateIntervalEnum = typeof PriceCreateIntervalEnum[keyof typeof PriceCreateIntervalEnum];


/**
 * Check if a given object implements the PriceCreate interface.
 */
export function instanceOfPriceCreate(value: object): value is PriceCreate {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    return true;
}

export function PriceCreateFromJSON(json: any): PriceCreate {
    return PriceCreateFromJSONTyped(json, false);
}

export function PriceCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'productId': json['productId'],
        'amount': json['amount'],
        'interval': json['interval'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function PriceCreateToJSON(json: any): PriceCreate {
    return PriceCreateToJSONTyped(json, false);
}

export function PriceCreateToJSONTyped(value?: PriceCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'productId': value['productId'],
        'amount': value['amount'],
        'interval': value['interval'],
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

