/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceUpdateAmount } from './PriceUpdateAmount';
import {
    PriceUpdateAmountFromJSON,
    PriceUpdateAmountFromJSONTyped,
    PriceUpdateAmountToJSON,
    PriceUpdateAmountToJSONTyped,
} from './PriceUpdateAmount';

/**
 * 
 * @export
 * @interface PriceUpdate
 */
export interface PriceUpdate {
    /**
     * 
     * @type {PriceUpdateAmount}
     * @memberof PriceUpdate
     */
    amount?: PriceUpdateAmount;
    /**
     * 
     * @type {PriceUpdateIntervalEnum}
     * @memberof PriceUpdate
     */
    interval?: PriceUpdateIntervalEnum;
    /**
     * 
     * @type {boolean}
     * @memberof PriceUpdate
     */
    replaceExisting?: boolean;
}


/**
 * @export
 */
export const PriceUpdateIntervalEnum = {
    Weekly: 'weekly',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type PriceUpdateIntervalEnum = typeof PriceUpdateIntervalEnum[keyof typeof PriceUpdateIntervalEnum];


/**
 * Check if a given object implements the PriceUpdate interface.
 */
export function instanceOfPriceUpdate(value: object): value is PriceUpdate {
    return true;
}

export function PriceUpdateFromJSON(json: any): PriceUpdate {
    return PriceUpdateFromJSONTyped(json, false);
}

export function PriceUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : PriceUpdateAmountFromJSON(json['amount']),
        'interval': json['interval'] == null ? undefined : json['interval'],
        'replaceExisting': json['replaceExisting'] == null ? undefined : json['replaceExisting'],
    };
}

export function PriceUpdateToJSON(json: any): PriceUpdate {
    return PriceUpdateToJSONTyped(json, false);
}

export function PriceUpdateToJSONTyped(value?: PriceUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': PriceUpdateAmountToJSON(value['amount']),
        'interval': value['interval'],
        'replaceExisting': value['replaceExisting'],
    };
}

