/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceUpdateAmount
 */
export interface PriceUpdateAmount {
}

/**
 * Check if a given object implements the PriceUpdateAmount interface.
 */
export function instanceOfPriceUpdateAmount(value: object): value is PriceUpdateAmount {
    return true;
}

export function PriceUpdateAmountFromJSON(json: any): PriceUpdateAmount {
    return PriceUpdateAmountFromJSONTyped(json, false);
}

export function PriceUpdateAmountFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceUpdateAmount {
    return json;
}

export function PriceUpdateAmountToJSON(json: any): PriceUpdateAmount {
    return PriceUpdateAmountToJSONTyped(json, false);
}

export function PriceUpdateAmountToJSONTyped(value?: PriceUpdateAmount | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

