/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductGetWithPricesDataPricesInner } from './ProductGetWithPricesDataPricesInner';
import {
    ProductGetWithPricesDataPricesInnerFromJSON,
    ProductGetWithPricesDataPricesInnerFromJSONTyped,
    ProductGetWithPricesDataPricesInnerToJSON,
    ProductGetWithPricesDataPricesInnerToJSONTyped,
} from './ProductGetWithPricesDataPricesInner';

/**
 * 
 * @export
 * @interface PriceGet
 */
export interface PriceGet {
    /**
     * 
     * @type {ProductGetWithPricesDataPricesInner}
     * @memberof PriceGet
     */
    data: ProductGetWithPricesDataPricesInner;
}

/**
 * Check if a given object implements the PriceGet interface.
 */
export function instanceOfPriceGet(value: object): value is PriceGet {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PriceGetFromJSON(json: any): PriceGet {
    return PriceGetFromJSONTyped(json, false);
}

export function PriceGetFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceGet {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ProductGetWithPricesDataPricesInnerFromJSON(json['data']),
    };
}

export function PriceGetToJSON(json: any): PriceGet {
    return PriceGetToJSONTyped(json, false);
}

export function PriceGetToJSONTyped(value?: PriceGet | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ProductGetWithPricesDataPricesInnerToJSON(value['data']),
    };
}

