/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductGetData
 */
export interface ProductGetData {
    /**
     * 
     * @type {string}
     * @memberof ProductGetData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetData
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetData
     */
    environmentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductGetData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetData
     */
    description: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductGetData
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProductGetData
     */
    createdAt: Date | null;
}

/**
 * Check if a given object implements the ProductGetData interface.
 */
export function instanceOfProductGetData(value: object): value is ProductGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('environmentId' in value) || value['environmentId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProductGetDataFromJSON(json: any): ProductGetData {
    return ProductGetDataFromJSONTyped(json, false);
}

export function ProductGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'environmentId': json['environmentId'],
        'name': json['name'],
        'description': json['description'],
        'active': json['active'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
    };
}

export function ProductGetDataToJSON(json: any): ProductGetData {
    return ProductGetDataToJSONTyped(json, false);
}

export function ProductGetDataToJSONTyped(value?: ProductGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'environmentId': value['environmentId'],
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

