/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductListPagination
 */
export interface ProductListPagination {
    /**
     * 
     * @type {number}
     * @memberof ProductListPagination
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof ProductListPagination
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof ProductListPagination
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof ProductListPagination
     */
    totalPages: number;
}

/**
 * Check if a given object implements the ProductListPagination interface.
 */
export function instanceOfProductListPagination(value: object): value is ProductListPagination {
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function ProductListPaginationFromJSON(json: any): ProductListPagination {
    return ProductListPaginationFromJSONTyped(json, false);
}

export function ProductListPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListPagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'],
        'limit': json['limit'],
        'total': json['total'],
        'totalPages': json['totalPages'],
    };
}

export function ProductListPaginationToJSON(json: any): ProductListPagination {
    return ProductListPaginationToJSONTyped(json, false);
}

export function ProductListPaginationToJSONTyped(value?: ProductListPagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'totalPages': value['totalPages'],
    };
}

