/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductListPagination } from './ProductListPagination';
import {
    ProductListPaginationFromJSON,
    ProductListPaginationFromJSONTyped,
    ProductListPaginationToJSON,
    ProductListPaginationToJSONTyped,
} from './ProductListPagination';
import type { ProductGetWithPricesData } from './ProductGetWithPricesData';
import {
    ProductGetWithPricesDataFromJSON,
    ProductGetWithPricesDataFromJSONTyped,
    ProductGetWithPricesDataToJSON,
    ProductGetWithPricesDataToJSONTyped,
} from './ProductGetWithPricesData';

/**
 * 
 * @export
 * @interface ProductList
 */
export interface ProductList {
    /**
     * 
     * @type {Array<ProductGetWithPricesData>}
     * @memberof ProductList
     */
    data: Array<ProductGetWithPricesData>;
    /**
     * 
     * @type {ProductListPagination}
     * @memberof ProductList
     */
    pagination: ProductListPagination;
}

/**
 * Check if a given object implements the ProductList interface.
 */
export function instanceOfProductList(value: object): value is ProductList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function ProductListFromJSON(json: any): ProductList {
    return ProductListFromJSONTyped(json, false);
}

export function ProductListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProductGetWithPricesDataFromJSON)),
        'pagination': ProductListPaginationFromJSON(json['pagination']),
    };
}

export function ProductListToJSON(json: any): ProductList {
    return ProductListToJSONTyped(json, false);
}

export function ProductListToJSONTyped(value?: ProductList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ProductGetWithPricesDataToJSON)),
        'pagination': ProductListPaginationToJSON(value['pagination']),
    };
}

