/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductUpdate
 */
export interface ProductUpdate {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdate
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductUpdate
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProductUpdate
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the ProductUpdate interface.
 */
export function instanceOfProductUpdate(value: object): value is ProductUpdate {
    return true;
}

export function ProductUpdateFromJSON(json: any): ProductUpdate {
    return ProductUpdateFromJSONTyped(json, false);
}

export function ProductUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
    };
}

export function ProductUpdateToJSON(json: any): ProductUpdate {
    return ProductUpdateToJSONTyped(json, false);
}

export function ProductUpdateToJSONTyped(value?: ProductUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

