/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductGetWithPricesDataPricesInner
 */
export interface ProductGetWithPricesDataPricesInner {
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesDataPricesInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesDataPricesInner
     */
    productId: string;
    /**
     * 
     * @type {number}
     * @memberof ProductGetWithPricesDataPricesInner
     */
    amount: number;
    /**
     * 
     * @type {ProductGetWithPricesDataPricesInnerIntervalEnum}
     * @memberof ProductGetWithPricesDataPricesInner
     */
    interval: ProductGetWithPricesDataPricesInnerIntervalEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ProductGetWithPricesDataPricesInner
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProductGetWithPricesDataPricesInner
     */
    createdAt: Date | null;
}


/**
 * @export
 */
export const ProductGetWithPricesDataPricesInnerIntervalEnum = {
    Weekly: 'weekly',
    Monthly: 'monthly',
    Yearly: 'yearly'
} as const;
export type ProductGetWithPricesDataPricesInnerIntervalEnum = typeof ProductGetWithPricesDataPricesInnerIntervalEnum[keyof typeof ProductGetWithPricesDataPricesInnerIntervalEnum];


/**
 * Check if a given object implements the ProductGetWithPricesDataPricesInner interface.
 */
export function instanceOfProductGetWithPricesDataPricesInner(value: object): value is ProductGetWithPricesDataPricesInner {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function ProductGetWithPricesDataPricesInnerFromJSON(json: any): ProductGetWithPricesDataPricesInner {
    return ProductGetWithPricesDataPricesInnerFromJSONTyped(json, false);
}

export function ProductGetWithPricesDataPricesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductGetWithPricesDataPricesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'productId': json['productId'],
        'amount': json['amount'],
        'interval': json['interval'],
        'active': json['active'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
    };
}

export function ProductGetWithPricesDataPricesInnerToJSON(json: any): ProductGetWithPricesDataPricesInner {
    return ProductGetWithPricesDataPricesInnerToJSONTyped(json, false);
}

export function ProductGetWithPricesDataPricesInnerToJSONTyped(value?: ProductGetWithPricesDataPricesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'productId': value['productId'],
        'amount': value['amount'],
        'interval': value['interval'],
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

