/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductGetWithPricesData } from './ProductGetWithPricesData';
import {
    ProductGetWithPricesDataFromJSON,
    ProductGetWithPricesDataFromJSONTyped,
    ProductGetWithPricesDataToJSON,
    ProductGetWithPricesDataToJSONTyped,
} from './ProductGetWithPricesData';

/**
 * 
 * @export
 * @interface ProductGetWithPrices
 */
export interface ProductGetWithPrices {
    /**
     * 
     * @type {ProductGetWithPricesData}
     * @memberof ProductGetWithPrices
     */
    data: ProductGetWithPricesData;
}

/**
 * Check if a given object implements the ProductGetWithPrices interface.
 */
export function instanceOfProductGetWithPrices(value: object): value is ProductGetWithPrices {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ProductGetWithPricesFromJSON(json: any): ProductGetWithPrices {
    return ProductGetWithPricesFromJSONTyped(json, false);
}

export function ProductGetWithPricesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductGetWithPrices {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ProductGetWithPricesDataFromJSON(json['data']),
    };
}

export function ProductGetWithPricesToJSON(json: any): ProductGetWithPrices {
    return ProductGetWithPricesToJSONTyped(json, false);
}

export function ProductGetWithPricesToJSONTyped(value?: ProductGetWithPrices | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ProductGetWithPricesDataToJSON(value['data']),
    };
}

