/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ProductCreate
 */
export interface ProductCreate {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    description?: string | null;
    /**
     * 
     */
    active?: boolean;
    /**
     * 
     */
    createdAt?: Date | null;
}

/**
 * Check if a given object implements the ProductCreate interface.
 */
export function instanceOfProductCreate(value: object): value is ProductCreate {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProductCreateFromJSON(json: any): ProductCreate {
    return ProductCreateFromJSONTyped(json, false);
}

export function ProductCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'active': json['active'] == null ? undefined : json['active'],
        'createdAt': json['createdAt'] === undefined ? undefined : json['createdAt'] === null ? null : (parseDateTime(json['createdAt'])),
    };
}

export function ProductCreateToJSON(json: any): ProductCreate {
    return ProductCreateToJSONTyped(json, false);
}

export function ProductCreateToJSONTyped(value?: ProductCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
    };
}

