/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductGetWithPricesDataPricesInner } from './ProductGetWithPricesDataPricesInner';
import {
    ProductGetWithPricesDataPricesInnerFromJSON,
    ProductGetWithPricesDataPricesInnerFromJSONTyped,
    ProductGetWithPricesDataPricesInnerToJSON,
    ProductGetWithPricesDataPricesInnerToJSONTyped,
} from './ProductGetWithPricesDataPricesInner';

/**
 * 
 * @export
 * @interface ProductGetWithPricesData
 */
export interface ProductGetWithPricesData {
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesData
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesData
     */
    environmentId: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductGetWithPricesData
     */
    description: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductGetWithPricesData
     */
    active: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ProductGetWithPricesData
     */
    createdAt: Date | null;
    /**
     * 
     * @type {Array<ProductGetWithPricesDataPricesInner>}
     * @memberof ProductGetWithPricesData
     */
    prices: Array<ProductGetWithPricesDataPricesInner>;
}

/**
 * Check if a given object implements the ProductGetWithPricesData interface.
 */
export function instanceOfProductGetWithPricesData(value: object): value is ProductGetWithPricesData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('environmentId' in value) || value['environmentId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('prices' in value) || value['prices'] === undefined) return false;
    return true;
}

export function ProductGetWithPricesDataFromJSON(json: any): ProductGetWithPricesData {
    return ProductGetWithPricesDataFromJSONTyped(json, false);
}

export function ProductGetWithPricesDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductGetWithPricesData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'environmentId': json['environmentId'],
        'name': json['name'],
        'description': json['description'],
        'active': json['active'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
        'prices': ((json['prices'] as Array<any>).map(ProductGetWithPricesDataPricesInnerFromJSON)),
    };
}

export function ProductGetWithPricesDataToJSON(json: any): ProductGetWithPricesData {
    return ProductGetWithPricesDataToJSONTyped(json, false);
}

export function ProductGetWithPricesDataToJSONTyped(value?: ProductGetWithPricesData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'environmentId': value['environmentId'],
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'prices': ((value['prices'] as Array<any>).map(ProductGetWithPricesDataPricesInnerToJSON)),
    };
}

