/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionGetData
 */
export interface SubscriptionGetData {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionGetData
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionGetData
     */
    organizationId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionGetData
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionGetData
     */
    priceId: string;
    /**
     * 
     * @type {SubscriptionGetDataStatusEnum}
     * @memberof SubscriptionGetData
     */
    status: SubscriptionGetDataStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionGetData
     */
    nextBillingDate: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionGetData
     */
    startedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionGetData
     */
    cancelledAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionGetData
     */
    expiresAt: Date | null;
}


/**
 * @export
 */
export const SubscriptionGetDataStatusEnum = {
    Trialing: 'trialing',
    Active: 'active',
    PastDue: 'past_due',
    Paused: 'paused',
    Cancelled: 'cancelled',
    Expired: 'expired',
    PendingCancellation: 'pending_cancellation'
} as const;
export type SubscriptionGetDataStatusEnum = typeof SubscriptionGetDataStatusEnum[keyof typeof SubscriptionGetDataStatusEnum];


/**
 * Check if a given object implements the SubscriptionGetData interface.
 */
export function instanceOfSubscriptionGetData(value: object): value is SubscriptionGetData {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('organizationId' in value) || value['organizationId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('nextBillingDate' in value) || value['nextBillingDate'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('cancelledAt' in value) || value['cancelledAt'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function SubscriptionGetDataFromJSON(json: any): SubscriptionGetData {
    return SubscriptionGetDataFromJSONTyped(json, false);
}

export function SubscriptionGetDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionGetData {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'organizationId': json['organizationId'],
        'customerId': json['customerId'],
        'priceId': json['priceId'],
        'status': json['status'],
        'nextBillingDate': (json['nextBillingDate'] == null ? null : new Date(json['nextBillingDate'])),
        'startedAt': (json['startedAt'] == null ? null : new Date(json['startedAt'])),
        'cancelledAt': (json['cancelledAt'] == null ? null : new Date(json['cancelledAt'])),
        'expiresAt': (json['expiresAt'] == null ? null : new Date(json['expiresAt'])),
    };
}

export function SubscriptionGetDataToJSON(json: any): SubscriptionGetData {
    return SubscriptionGetDataToJSONTyped(json, false);
}

export function SubscriptionGetDataToJSONTyped(value?: SubscriptionGetData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'organizationId': value['organizationId'],
        'customerId': value['customerId'],
        'priceId': value['priceId'],
        'status': value['status'],
        'nextBillingDate': value['nextBillingDate'] == null ? value['nextBillingDate'] : value['nextBillingDate'].toISOString(),
        'startedAt': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

