/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionCreateTrial
 */
export interface SubscriptionCreateTrial {
}

/**
 * Check if a given object implements the SubscriptionCreateTrial interface.
 */
export function instanceOfSubscriptionCreateTrial(value: object): value is SubscriptionCreateTrial {
    return true;
}

export function SubscriptionCreateTrialFromJSON(json: any): SubscriptionCreateTrial {
    return SubscriptionCreateTrialFromJSONTyped(json, false);
}

export function SubscriptionCreateTrialFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreateTrial {
    return json;
}

export function SubscriptionCreateTrialToJSON(json: any): SubscriptionCreateTrial {
    return SubscriptionCreateTrialToJSONTyped(json, false);
}

export function SubscriptionCreateTrialToJSONTyped(value?: SubscriptionCreateTrial | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

