/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionCreateTrialEnd } from './SubscriptionCreateTrialEnd';
import {
    SubscriptionCreateTrialEndFromJSON,
    SubscriptionCreateTrialEndFromJSONTyped,
    SubscriptionCreateTrialEndToJSON,
    SubscriptionCreateTrialEndToJSONTyped,
} from './SubscriptionCreateTrialEnd';
import type { SubscriptionCreateTrial } from './SubscriptionCreateTrial';
import {
    SubscriptionCreateTrialFromJSON,
    SubscriptionCreateTrialFromJSONTyped,
    SubscriptionCreateTrialToJSON,
    SubscriptionCreateTrialToJSONTyped,
} from './SubscriptionCreateTrial';

/**
 * 
 * @export
 * @interface SubscriptionCreate
 */
export interface SubscriptionCreate {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreate
     */
    priceId: string;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionCreate
     */
    cancelledAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionCreate
     */
    expiresAt?: Date | null;
    /**
     * 
     * @type {SubscriptionCreateTrial}
     * @memberof SubscriptionCreate
     */
    trial?: SubscriptionCreateTrial;
    /**
     * 
     * @type {SubscriptionCreateTrialPeriodEnum}
     * @memberof SubscriptionCreate
     */
    trialPeriod?: SubscriptionCreateTrialPeriodEnum;
    /**
     * 
     * @type {SubscriptionCreateTrialEnd}
     * @memberof SubscriptionCreate
     */
    trialEnd?: SubscriptionCreateTrialEnd;
    /**
     * 
     * @type {SubscriptionCreateTrialEnd}
     * @memberof SubscriptionCreate
     */
    startedAt?: SubscriptionCreateTrialEnd;
}


/**
 * @export
 */
export const SubscriptionCreateTrialPeriodEnum = {
    _1Week: '1_week',
    _1Month: '1_month',
    _1Year: '1_year'
} as const;
export type SubscriptionCreateTrialPeriodEnum = typeof SubscriptionCreateTrialPeriodEnum[keyof typeof SubscriptionCreateTrialPeriodEnum];


/**
 * Check if a given object implements the SubscriptionCreate interface.
 */
export function instanceOfSubscriptionCreate(value: object): value is SubscriptionCreate {
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    return true;
}

export function SubscriptionCreateFromJSON(json: any): SubscriptionCreate {
    return SubscriptionCreateFromJSONTyped(json, false);
}

export function SubscriptionCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'customerId': json['customerId'],
        'priceId': json['priceId'],
        'cancelledAt': json['cancelledAt'] == null ? undefined : (new Date(json['cancelledAt'])),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'trial': json['trial'] == null ? undefined : SubscriptionCreateTrialFromJSON(json['trial']),
        'trialPeriod': json['trialPeriod'] == null ? undefined : json['trialPeriod'],
        'trialEnd': json['trialEnd'] == null ? undefined : SubscriptionCreateTrialEndFromJSON(json['trialEnd']),
        'startedAt': json['startedAt'] == null ? undefined : SubscriptionCreateTrialEndFromJSON(json['startedAt']),
    };
}

export function SubscriptionCreateToJSON(json: any): SubscriptionCreate {
    return SubscriptionCreateToJSONTyped(json, false);
}

export function SubscriptionCreateToJSONTyped(value?: SubscriptionCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'customerId': value['customerId'],
        'priceId': value['priceId'],
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : value['cancelledAt'].toISOString(),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'trial': SubscriptionCreateTrialToJSON(value['trial']),
        'trialPeriod': value['trialPeriod'],
        'trialEnd': SubscriptionCreateTrialEndToJSON(value['trialEnd']),
        'startedAt': SubscriptionCreateTrialEndToJSON(value['startedAt']),
    };
}

