/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionCreateTrialEnd
 */
export interface SubscriptionCreateTrialEnd {
}

/**
 * Check if a given object implements the SubscriptionCreateTrialEnd interface.
 */
export function instanceOfSubscriptionCreateTrialEnd(value: object): value is SubscriptionCreateTrialEnd {
    return true;
}

export function SubscriptionCreateTrialEndFromJSON(json: any): SubscriptionCreateTrialEnd {
    return SubscriptionCreateTrialEndFromJSONTyped(json, false);
}

export function SubscriptionCreateTrialEndFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreateTrialEnd {
    return json;
}

export function SubscriptionCreateTrialEndToJSON(json: any): SubscriptionCreateTrialEnd {
    return SubscriptionCreateTrialEndToJSONTyped(json, false);
}

export function SubscriptionCreateTrialEndToJSONTyped(value?: SubscriptionCreateTrialEnd | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

