/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionCreateTrialEnd } from './SubscriptionCreateTrialEnd';
import {
    SubscriptionCreateTrialEndFromJSON,
    SubscriptionCreateTrialEndFromJSONTyped,
    SubscriptionCreateTrialEndToJSON,
    SubscriptionCreateTrialEndToJSONTyped,
} from './SubscriptionCreateTrialEnd';
import type { SubscriptionCreateTrial } from './SubscriptionCreateTrial';
import {
    SubscriptionCreateTrialFromJSON,
    SubscriptionCreateTrialFromJSONTyped,
    SubscriptionCreateTrialToJSON,
    SubscriptionCreateTrialToJSONTyped,
} from './SubscriptionCreateTrial';

/**
 * 
 * @export
 * @interface SubscriptionCreateByExternalUser
 */
export interface SubscriptionCreateByExternalUser {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateByExternalUser
     */
    externalUserId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateByExternalUser
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionCreateByExternalUser
     */
    priceId: string;
    /**
     * 
     * @type {SubscriptionCreateTrial}
     * @memberof SubscriptionCreateByExternalUser
     */
    trial?: SubscriptionCreateTrial;
    /**
     * 
     * @type {SubscriptionCreateByExternalUserTrialPeriodEnum}
     * @memberof SubscriptionCreateByExternalUser
     */
    trialPeriod?: SubscriptionCreateByExternalUserTrialPeriodEnum;
    /**
     * 
     * @type {SubscriptionCreateTrialEnd}
     * @memberof SubscriptionCreateByExternalUser
     */
    trialEnd?: SubscriptionCreateTrialEnd;
    /**
     * 
     * @type {SubscriptionCreateTrialEnd}
     * @memberof SubscriptionCreateByExternalUser
     */
    startedAt?: SubscriptionCreateTrialEnd;
    /**
     * 
     * @type {SubscriptionCreateTrialEnd}
     * @memberof SubscriptionCreateByExternalUser
     */
    expiresAt?: SubscriptionCreateTrialEnd;
}


/**
 * @export
 */
export const SubscriptionCreateByExternalUserTrialPeriodEnum = {
    _1Week: '1_week',
    _1Month: '1_month',
    _1Year: '1_year'
} as const;
export type SubscriptionCreateByExternalUserTrialPeriodEnum = typeof SubscriptionCreateByExternalUserTrialPeriodEnum[keyof typeof SubscriptionCreateByExternalUserTrialPeriodEnum];


/**
 * Check if a given object implements the SubscriptionCreateByExternalUser interface.
 */
export function instanceOfSubscriptionCreateByExternalUser(value: object): value is SubscriptionCreateByExternalUser {
    if (!('externalUserId' in value) || value['externalUserId'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    return true;
}

export function SubscriptionCreateByExternalUserFromJSON(json: any): SubscriptionCreateByExternalUser {
    return SubscriptionCreateByExternalUserFromJSONTyped(json, false);
}

export function SubscriptionCreateByExternalUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionCreateByExternalUser {
    if (json == null) {
        return json;
    }
    return {
        
        'externalUserId': json['externalUserId'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'priceId': json['priceId'],
        'trial': json['trial'] == null ? undefined : SubscriptionCreateTrialFromJSON(json['trial']),
        'trialPeriod': json['trialPeriod'] == null ? undefined : json['trialPeriod'],
        'trialEnd': json['trialEnd'] == null ? undefined : SubscriptionCreateTrialEndFromJSON(json['trialEnd']),
        'startedAt': json['startedAt'] == null ? undefined : SubscriptionCreateTrialEndFromJSON(json['startedAt']),
        'expiresAt': json['expiresAt'] == null ? undefined : SubscriptionCreateTrialEndFromJSON(json['expiresAt']),
    };
}

export function SubscriptionCreateByExternalUserToJSON(json: any): SubscriptionCreateByExternalUser {
    return SubscriptionCreateByExternalUserToJSONTyped(json, false);
}

export function SubscriptionCreateByExternalUserToJSONTyped(value?: SubscriptionCreateByExternalUser | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalUserId': value['externalUserId'],
        'phone': value['phone'],
        'priceId': value['priceId'],
        'trial': SubscriptionCreateTrialToJSON(value['trial']),
        'trialPeriod': value['trialPeriod'],
        'trialEnd': SubscriptionCreateTrialEndToJSON(value['trialEnd']),
        'startedAt': SubscriptionCreateTrialEndToJSON(value['startedAt']),
        'expiresAt': SubscriptionCreateTrialEndToJSON(value['expiresAt']),
    };
}

