/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionGetData } from './SubscriptionGetData';
import {
    SubscriptionGetDataFromJSON,
    SubscriptionGetDataFromJSONTyped,
    SubscriptionGetDataToJSON,
    SubscriptionGetDataToJSONTyped,
} from './SubscriptionGetData';
import type { ProductListPagination } from './ProductListPagination';
import {
    ProductListPaginationFromJSON,
    ProductListPaginationFromJSONTyped,
    ProductListPaginationToJSON,
    ProductListPaginationToJSONTyped,
} from './ProductListPagination';

/**
 * 
 * @export
 * @interface SubscriptionList
 */
export interface SubscriptionList {
    /**
     * 
     * @type {Array<SubscriptionGetData>}
     * @memberof SubscriptionList
     */
    data: Array<SubscriptionGetData>;
    /**
     * 
     * @type {ProductListPagination}
     * @memberof SubscriptionList
     */
    pagination: ProductListPagination;
}

/**
 * Check if a given object implements the SubscriptionList interface.
 */
export function instanceOfSubscriptionList(value: object): value is SubscriptionList {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('pagination' in value) || value['pagination'] === undefined) return false;
    return true;
}

export function SubscriptionListFromJSON(json: any): SubscriptionList {
    return SubscriptionListFromJSONTyped(json, false);
}

export function SubscriptionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionList {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(SubscriptionGetDataFromJSON)),
        'pagination': ProductListPaginationFromJSON(json['pagination']),
    };
}

export function SubscriptionListToJSON(json: any): SubscriptionList {
    return SubscriptionListToJSONTyped(json, false);
}

export function SubscriptionListToJSONTyped(value?: SubscriptionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(SubscriptionGetDataToJSON)),
        'pagination': ProductListPaginationToJSON(value['pagination']),
    };
}

