/* tslint:disable */
/* eslint-disable */
/**
 * Moosyl API
 * The Moosyl API is a powerful API for integrating payment solutions with Mauritania\'s popular banking apps, such as Bankily, Sedad, and Masrivi. Simplify the payment process in your Flutter applications with features like webhooks and an easy-to-use client SDKs.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionUpdate
 */
export interface SubscriptionUpdate {
    /**
     * 
     */
    priceId?: string;
    /**
     * 
     */
    status?: SubscriptionUpdateStatusEnum;
    /**
     * 
     */
    nextBillingDate?: Date | null;
    /**
     * 
     */
    cancelledAt?: Date | null;
    /**
     * 
     */
    expiresAt?: Date | null;
}


/**
 * @export
 */
export const SubscriptionUpdateStatusEnum = {
    Trialing: 'trialing',
    Active: 'active',
    PastDue: 'past_due',
    Paused: 'paused',
    Cancelled: 'cancelled',
    Expired: 'expired',
    PendingCancellation: 'pending_cancellation',
} as const;
export type SubscriptionUpdateStatusEnum = typeof SubscriptionUpdateStatusEnum[keyof typeof SubscriptionUpdateStatusEnum];


/**
 * Check if a given object implements the SubscriptionUpdate interface.
 */
export function instanceOfSubscriptionUpdate(value: object): value is SubscriptionUpdate {
    return true;
}

export function SubscriptionUpdateFromJSON(json: any): SubscriptionUpdate {
    return SubscriptionUpdateFromJSONTyped(json, false);
}

export function SubscriptionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['priceId'] == null ? undefined : json['priceId'],
        'status': json['status'] == null ? undefined : json['status'],
        'nextBillingDate': json['nextBillingDate'] === undefined ? undefined : json['nextBillingDate'] === null ? null : (parseDateTime(json['nextBillingDate'])),
        'cancelledAt': json['cancelledAt'] === undefined ? undefined : json['cancelledAt'] === null ? null : (parseDateTime(json['cancelledAt'])),
        'expiresAt': json['expiresAt'] === undefined ? undefined : json['expiresAt'] === null ? null : (parseDateTime(json['expiresAt'])),
    };
}

export function SubscriptionUpdateToJSON(json: any): SubscriptionUpdate {
    return SubscriptionUpdateToJSONTyped(json, false);
}

export function SubscriptionUpdateToJSONTyped(value?: SubscriptionUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceId': value['priceId'],
        'status': value['status'],
        'nextBillingDate': value['nextBillingDate'] == null ? value['nextBillingDate'] : serializeDateTime(value['nextBillingDate']),
        'cancelledAt': value['cancelledAt'] == null ? value['cancelledAt'] : serializeDateTime(value['cancelledAt']),
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : serializeDateTime(value['expiresAt']),
    };
}

